### ISSUE TITLE
tight_layout and font hinting cuts text near the edge

### ISSUE THREAD

**Issue by prekageo** [matplotlib/matplotlib#11551]
### Bug report

I plot a figure with default configuration. I use 8 point fonts and tight_layout. In the resulting PDF, the x and y labels are cut.

**Code for reproduction**

```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt

matplotlib.rcParams['font.size'] = 8
# matplotlib.rcParams['text.hinting'] = 'none' # uncomment to fix problem

plt.figure(figsize=(.5,.5))
plt.xlabel('qyg')
plt.ylabel('ETZ')
plt.yticks([])
plt.xticks([])
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['top'].set_visible(False)
plt.gca().spines['bottom'].set_visible(False)
plt.gca().spines['left'].set_visible(False)
plt.tight_layout(pad=0)
plt.savefig('output.pdf')
```

**Actual outcome**

[bad.pdf](https://github.com/matplotlib/matplotlib/files/2155253/bad.pdf)

**Expected outcome**

[good.pdf](https://github.com/matplotlib/matplotlib/files/2155254/good.pdf)

**Matplotlib version**

  * Operating system: Ubuntu 16.04.2 LTS
  * Matplotlib version: commit 0f05cf47c5f23729bc82bca25de30f39c57658fd
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.5.2
  * Jupyter version (if applicable):
  * Other libraries: 

The font used is the default matplotlib font:
```
$ md5sum DejaVuSans.ttf
49c0f03ec2fa354df7002bcb6331e106  DejaVuSans.ttf
```

I believe that the problem is here:
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_agg.py#L232
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_pdf.py#L2144

As you can see the PDF backend always uses LOAD_NO_HINTING while the Agg backend uses whatever the user specifies. The only workaround that I've found is enabling the commented out line in the testcase above.

**Comment by prekageo** [comment]
For anyone who might try to resolve this issue, the relevant lines of code have changed. For the current master 303d5159f62d52455ee439ea203e14e2158231a0, the lines are:
https://github.com/matplotlib/matplotlib/blob/303d5159f62d52455ee439ea203e14e2158231a0/lib/matplotlib/backends/_backend_pdf_ps.py#L102
https://github.com/matplotlib/matplotlib/blob/303d5159f62d52455ee439ea203e14e2158231a0/lib/matplotlib/backends/backend_agg.py#L180

**Comment by oscargus** [comment]
This seems to have been solved. The current output is:
![image](https://user-images.githubusercontent.com/8114497/171954233-343b4467-e884-4609-9329-bce4c16cf237.png)

(The black border is to make it more clear how much padding there is, indeed a bit more than in the "good.pdf" in the OP.)

**Comment by prekageo** [comment]
I just tested with the latest main (80015796eddd2e47013ded76718603da40192595) and I still see the same problem. Can you share your reproduction script? Maybe the border fixes the original problem?

**Comment by prekageo** [comment]
I just tested with the latest main (80015796eddd2e47013ded76718603da40192595) and I still see the same problem. Can you share your reproduction script? Maybe the border fixes the original problem?

And it looks like I do not have access to reopen this issue so tagging @oscargus if he could reopen it. Thanks!

**Comment by oscargus** [comment]
> Can you share your reproduction script? Maybe the border fixes the original problem?

Sorry, didn't see this until now. I used exactly the same script as here (without anything in the matplotlibrc file IIRC). I was a bit unclear about the border though. That is the background from the PDF viewer (Drawboard PDF, hence the black background.) Seems to work for me with Acrobat reader, Firefox, Chrome and Edge as well.

**Comment by prekageo** [comment]
Sorry for the delay.

@jklymak Using `constrained`, the problem goes away.

@oscargus I've opened the attached PDF (https://github.com/matplotlib/matplotlib/files/2155253/bad.pdf) with Acrobat, Firefox and Chrome and it renders in the same way in all 3. The letters are cut near the edge. Can you share your generated PDF? I also opened it with Drawboard online (https://pdf.drawboard.com/documents/5d847711eca34829aabf472a0db7b759) and the text is still cut.

**Comment by george-enf** [comment]
Tested with 3.7.1. The problem is still here.

**Comment by prekageo** [comment]
Tested with latest main (bdbbb2dc50d9cf901e78a5bbcea8f458b757650d). The problem is still here. Note that a possible solution would be the following patch:
```patch
diff --git a/lib/matplotlib/mpl-data/matplotlibrc b/lib/matplotlib/mpl-data/matplotlibrc
index d419ed6..da30232 100644
--- a/lib/matplotlib/mpl-data/matplotlibrc
+++ b/lib/matplotlib/mpl-data/matplotlibrc
@@ -290,7 +290,7 @@
 ##                ("native" is a synonym.)
 ## - force_autohint: Use FreeType's auto-hinter.  ("auto" is a synonym.)
 ## - no_hinting: Disable hinting.  ("none" is a synonym.)
-#text.hinting: force_autohint
+#text.hinting: default

 #text.hinting_factor: 8  # Specifies the amount of softness for hinting in the
                          # horizontal direction.  A value of 1 will hint to full
```
It's worth noting that the change from `LOAD_DEFAULT` to `LOAD_FORCE_AUTOHINT` happened in commit 3299a39fff2e0143988e7112b10c3c0ae5392e10 by @mdboom.

**Comment by QuLogic** [comment]
#29816 will change hinting to default.
