### ISSUE TITLE
Unclear error when saving Animation using FFMpeg

### ISSUE THREAD

**Issue by AJJLagerweij** [matplotlib/matplotlib#12357]
### Bug report

**Bug summary**

Something goes wrong when I try to use the FFMpeg writer to write an animation. It used to work for me a couple of weeks ago and the error does not help to much either.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as anim

writer = anim.FFMpegWriter(fps=30, codec='libx264')

fig = plt.figure()
l, = plt.plot([], [], 'k-o')

plt.xlim(-5, 5)
plt.ylim(-5, 5)

x0, y0 = 0, 0

with writer.saving(fig, "writer_test.mp4", 100):
    for i in range(100):
        x0 += 0.1 * np.random.randn()
        y0 += 0.1 * np.random.randn()
        l.set_data(x0, y0)
        writer.grab_frame()
```

**Actual outcome**

```
 Traceback (most recent call last):

  File "<ipython-input-19-d9a5977378d9>", line 1, in <module>
    runfile('/home/bram/Documenten/TUDelft/Thesis/Phyton/test.py', wdir='/home/bram/Documenten/TUDelft/Thesis/Phyton')

  File "/home/bram/.anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 668, in runfile
    execfile(filename, namespace)

  File "/home/bram/.anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/bram/Documenten/TUDelft/Thesis/Phyton/test.py", line 31, in <module>
    writer.grab_frame()

  File "/home/bram/.anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)

  File "/home/bram/.anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()

  File "/home/bram/.anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 358, in finish
    self.cleanup()

  File "/home/bram/.anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 395, in cleanup
    out, err = self._proc.communicate()

  File "/home/bram/.anaconda3/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)

  File "/home/bram/.anaconda3/lib/python3.6/subprocess.py", line 1505, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)

  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)

  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)

  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)

  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None

ValueError: Invalid file object: <_io.BufferedReader name=55>
```

**Expected outcome**

I expect to obtain an .mp4 file which shows all the plots at 30fps. It does not do anything except giving the ```ValueError: Invalid file object: <_io.BufferedReader name=55>``` error. I might have used an older matlabcode previously but am not sure, I therefore tried an older version with conda but it did not help, it resulted in the same error.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.0 (from anaconda)
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6.6
  * Other libraries: ffmpeg 3.4.1 and 4.0.2, x264

I use conda to manage my environment using the default channel, for ffmpeg I tried both the standard and conda-forge channel.

**Comment by anntzer** [comment]
FWIW I cannot reproduce the failure locally (the example runs fine).

**Comment by ImportanceOfBeingErnest** [comment]
I cannot reproduce either. Creating a new environement via `conda create -n testenv3 matplotlib=3.0` (which will use python 3.6.6), the code runs fine.

**Comment by jklymak** [comment]
Can you run outside of spyder, just to keep the interactions minimal?

**Comment by AJJLagerweij** [comment]
I'll have a look at it tonight, I'm not sure how to run in conda environment outside spyder. How do I call it from the terminal?

**Comment by ImportanceOfBeingErnest** [comment]
Activate your conda environment `source activate base` where base could be a different environment if that applies. Then run the python script `python script.py`.

**Comment by AJJLagerweij** [comment]
Thanks for helping me, I do get a slightly different error,
```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    writer.grab_frame()
  File "/home/bram/.anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bram/.anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/home/bram/.anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 358, in finish
    self.cleanup()
  File "/home/bram/.anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 395, in cleanup
    out, err = self._proc.communicate()
  File "/home/bram/.anaconda3/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/bram/.anaconda3/lib/python3.6/subprocess.py", line 1505, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/home/bram/.anaconda3/lib/python3.6/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=12>
```
It might very well be that there is something wring with my environment, I'll try to make a new one and report on it, but the error given does not really help. I have no clue where to look at specificity.

**Comment by AJJLagerweij** [comment]
Even a new enviroment with only:
```
# packages in environment at /home/bram/.anaconda3/envs/Test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.03.07                    0  
certifi                   2018.8.24                py36_1  
cycler                    0.10.0                   py36_0  
dbus                      1.13.2               h714fa37_1  
expat                     2.2.6                he6710b0_0  
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
glib                      2.56.2               hd408876_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
icu                       58.2                 h9c2bf20_1  
intel-openmp              2019.0                      118  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.0.1            py36hf484d3e_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libopus                   1.2.1                hb9ed12e_0  
libpng                    1.6.34               hb9fc6fc_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
matplotlib                3.0.0            py36h5429711_0  
mkl                       2019.0                      118  
mkl_fft                   1.0.6            py36h7dd41cf_0  
mkl_random                1.0.1            py36h4414c95_1  
ncurses                   6.1                  hf484d3e_0  
numpy                     1.15.2           py36h1d66e8a_0  
numpy-base                1.15.2           py36h81de0dd_0  
openssl                   1.0.2p               h14c3975_0  
pcre                      8.42                 h439df22_0  
pip                       10.0.1                   py36_0  
pyparsing                 2.2.1                    py36_0  
pyqt                      5.9.2            py36h05f1152_2  
python                    3.6.6                hc3d631a_0  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.5                   py36_0  
qt                        5.9.6                h8703b6f_2  
readline                  7.0                  h7b6447c_5  
setuptools                40.2.0                   py36_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0                   py36_1  
sqlite                    3.25.2               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
tornado                   5.1.1            py36h7b6447c_0  
wheel                     0.31.1                   py36_0  
x264                      1!152.20180717       h470a237_1    conda-forge
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               ha838bed_2  
```
Returns the error for me:
```
  File "test.py", line 31, in <module>
    writer.grab_frame()
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/site-packages/matplotlib/animation.py", line 358, in finish
    self.cleanup()
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/site-packages/matplotlib/animation.py", line 395, in cleanup
    out, err = self._proc.communicate()
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/subprocess.py", line 1505, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/selectors.py", line 351, in register
    key = super().register(fileobj, events, data)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/selectors.py", line 237, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/selectors.py", line 224, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/selectors.py", line 39, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=12>
```

**Comment by ImportanceOfBeingErnest** [comment]
What happens if you use `anim.FFMpegFileWriter` instead? 

What is strange is that you get the error from line 31, but the example you show only has 20 lines.

**Comment by AJJLagerweij** [comment]
Dear Importance,

I made a mistake with the example code that I uploaded. The difference is in the documentation and the white space, causing errors at the ```writer.grab_frame()``` command. Below the full code that I'm working with:

```python
"""
===========
MovieWriter
===========

This example uses a MovieWriter directly to grab individual frames and write
them to a file. This avoids any event loop integration, but has the advantage
of working with even the Agg backend. This is not recommended for use in an
interactive setting.

"""
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as anim

writer = anim.FFMpegWriter(fps=30, codec='libx264')

fig = plt.figure()
l, = plt.plot([], [], 'k-o')

plt.xlim(-5, 5)
plt.ylim(-5, 5)

x0, y0 = 0, 0

with writer.saving(fig, "writer_test.mp4", 100):
    for i in range(100):
        x0 += 0.1 * np.random.randn()
        y0 += 0.1 * np.random.randn()
        l.set_data(x0, y0)
        writer.grab_frame()

```

Using the FFmpegFileWriter, replacing line 16 by  ```writer = anim.FFMpegFileWriter(fps=30, codec='libx264')``` causes a different error to appear:
```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    writer.grab_frame()
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/home/bram/.anaconda3/envs/Test/lib/python3.6/site-packages/matplotlib/animation.py", line 534, in finish
    .format(self._proc.returncode))
RuntimeError: Error creating movie, return code: 1
```

**Comment by anntzer** [comment]
I still cannot reproduce the failure...

**Comment by AJJLagerweij** [comment]
That most likely means that there is something wrong with my (new) environment, I just do not know what.

Besides it surprises me that the FFmpegFileWriter returns a RuntimeError while the FFmpegWriter shows a ValueError even though they fail at the same line.

**Comment by anntzer** [comment]
Likely you're also running into https://github.com/matplotlib/matplotlib/issues/9205n which doesn't help with error reporting...

**Comment by AJJLagerweij** [comment]
I do agree, I see the similarities between their and my problems.

**Comment by anntzer** [comment]
Hopefully https://github.com/matplotlib/matplotlib/pull/12368 and https://github.com/matplotlib/matplotlib/pull/12369 (once merged) will help, if you can try master...

**Comment by AJJLagerweij** [comment]
I have found that on my old enviroment in windows matplotlib 2.2.2 is used, which works without any issue. I'll try that version to on linux, and keep you posted.

**Comment by AJJLagerweij** [comment]
On windows both version 2.2.2 and 3.0.0 of matplotlib do work. On ubuntu they both fail. I'll try to reinstall python completly to see if that solves the problem.

**Comment by anntzer** [comment]
Are you able to compile matplotlib yourself?  If so the easiest would be to wait for #12369 to be merged (hopefully soon) (or just grab it from my fork, if you know how to do this) and try that (https://matplotlib.org/devel/contributing.html#retrieving-and-installing-the-latest-version-of-the-code).

**Comment by QuLogic** [comment]
I think you can enable logging `import logging; logging.basicConfig(level=logging.INFO)` which _might_ run before the exceptions in the related issues.

**Comment by anntzer** [comment]
I don't think there's a timeline for 3.1 yet.

**Comment by AJJLagerweij** [comment]
When using logging as proposed by QuLogic, some extra information appears just before the error:
```
INFO:matplotlib.animation:MovieWriter.run: running command: ['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '640x480', '-pix_fmt', 'rgba', '-r', '30', '-loglevel', 'quiet', '-i', 'pipe:', '-vcodec', 'libx264', '-y', 'writer_test.mp4']
INFO:matplotlib.animation:MovieWriter -- Error running proc:
b''
b''
```

**Comment by AJJLagerweij** [comment]
With all your advice and [StackOverflow](https://stackoverflow.com/questions/23074484/cannot-save-matplotlib-animation-with-ffmpeg) I managed to find a good workaround.

The real error happens somewhere in ffmpeg, which was derived from the errors when using ```import logging; logging.basicConfig(level=logging.INFO)``` and the discussion at #9205, and matplotlib is just unable to present this error.

The solution is relatively simple use ffmpeg from an other (non python) source and change the location that matplotlib uses to locate ffmpeg by adding `plt.rcParams['animation.ffmpeg_path'] = 'your_ffmpeg_location'` which for me was `'/usr/bin/ffmpeg'`.

Now I used the `ffmpeg -help` and `ffmpeg -codecs`  options in the terminal to see what options I had. These can be be accessed now through matplotlib. This allowed me to run `codec =hevc`, `codec=vp9` and many other options without issue.

Example code
```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as anim

plt.rcParams['animation.ffmpeg_path'] = '/usr/bin/ffmpeg'
writer = anim.FFMpegWriter(fps=30, codec='hevc')

fig = plt.figure()
l, = plt.plot([], [], 'k-o')

plt.xlim(-5, 5)
plt.ylim(-5, 5)

x0, y0 = 0, 0

with writer.saving(fig, "writer_test.mp4", 100):
    for i in range(100):
        x0 += 0.1 * np.random.randn()
        y0 += 0.1 * np.random.randn()
        l.set_data(x0, y0)
        writer.grab_frame()
```

**Comment by ImportanceOfBeingErnest** [comment]
Just to make sure, are there any default arguments to `FFMpegWriter` that would make this fail on linux? In other words, does matplotlib have to change anything here?

**Comment by AJJLagerweij** [comment]
For me the keyword that does not work is `codec`. But I cannot say for certain that is an matplotlib or ffmpeg issue but assume the problem is with ffmpeg.
I would like matplotlib to improve the error handling. But you seem to be aware of that already.

**Comment by AJJLagerweij** [comment]
For some reason the (python) integrated ffmpeg version, downloaded through conda works for some cases. After enabling `h264_nvec` (Nvidia hardware acceleration) it works fine. I expect something, don't know what to be wrong with the command given to ffmpeg when running the normal software based encoders. I'm not sure if that is somehow helpful your the matplotlib developers but at least now you know.

**Comment by anntzer** [comment]
At least the specific exception in the original report should be fixed by https://github.com/matplotlib/matplotlib/pull/12369.  Feel free to open a separate issue (including logging info) if there are additional problems using a version with that fix.

**Comment by akanksha95** [comment]
I have the same issue but the suggested solution (adding `plt.rcParams['animation.ffmpeg_path'] = 'your_ffmpeg_location'`) does not solve my problem.

**Comment by AJJLagerweij** [comment]
Oke, good to hear hat you managed to solve it.
It is not surprising that the reason of your error is different from mine. The problem that matplotlib.animation has is that it cannot (properly) handle errors/exceptions/logging that occur in ffmpeg, this means that the exceptions that python returns has little to no information to the cause of your error, other than that something went wrong in ffmpeg.
I have no clue however on how to improve the behavior, other than turning on `import logging; logging.basicConfig(level=logging.INFO)`.

**Comment by yuanzhedong** [comment]
I got same error in my conda env, the error is gone after reinstalling ffmpeg by `conda install -c conda-forge ffmpeg`
