### ISSUE TITLE
Trying to save an animated of graph with matplotlib in Python - "Invalid file object: <_io.BufferedReader name=76>"

### ISSUE THREAD

**Issue by bjce** [matplotlib/matplotlib#12769]
I tried to save an animated graph by reproducing the code from [this website][1]. I then tried to reproduce a code from [another website][2] which was similar but got the same message error "`Invalid file object: <_io.BufferedReader name=76>`".

I tried to run other codes available online for animated graph and got the same error. I updated the version of `ffmpeg` and installed `bzip2` with `conda install bzip2` but it didn't help. I also saw [this issue (#8760)](https://github.com/matplotlib/matplotlib/issues/8760) but it didn't help me (or I didn't understand what to do)

My settings are: 

macOS 10.14
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]
matplotlib: 2.1.0

What should I do?

Here is the code:

    import numpy as np
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.animation as animation

    def update_line(num, data, line):
        line.set_data(data[..., :num])
        return line,

    # Fixing random state for reproducibility
    np.random.seed(19680801)

    # Set up formatting for the movie files
    Writer = animation.writers['ffmpeg']
    writer = Writer(fps=15, metadata=dict(artist='Me'), bitrate=1800)

    fig1 = plt.figure()

    data = np.random.rand(2, 25)
    l, = plt.plot([], [], 'r-')
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.xlabel('x')
    plt.title('test')
    line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
                                   interval=50, blit=True)
    line_ani.save('lines.mp4', writer=writer)

    fig2 = plt.figure()

    x = np.arange(-9, 10)
    y = np.arange(-9, 10).reshape(-1, 1)
    base = np.hypot(x, y)
    ims = []
    for add in np.arange(15):
        ims.append((plt.pcolor(x, y, base + add, norm=plt.Normalize(0, 30)),))

    im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
    im_ani.save('im.mp4', writer=writer)

and got the following error message **(traceback n°1)**: 

    /anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: 
    This call to matplotlib.use() has no effect because the backend has already
    been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
    or matplotlib.backends is imported for the first time.

    The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
      File "/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
      File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
      File "/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
      File "/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
      File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
      File "/anaconda3/lib/python3.6/asyncio/base_events.py", line 1432, in _run_once
    handle._run()
      File "/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
      File "/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
      File "/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
      File "/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
      File "/anaconda3/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2666, in run_cell
    self.events.trigger('post_run_cell', result)
      File "/anaconda3/lib/python3.6/site-packages/IPython/core/events.py", line 88, in trigger
    func(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/ipykernel/pylab/backend_inline.py", line 160, in configure_once
    activate_matplotlib(backend)
      File "/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 311, in activate_matplotlib
    matplotlib.pyplot.switch_backend(backend)
      File "/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 229, in switch_backend
    matplotlib.use(newbackend, warn=False, force=True)
      File "/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1305, in use
    reload(sys.modules['matplotlib.backends'])
      File "/anaconda3/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
      File "/anaconda3/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()

          This is separate from the ipykernel package so we can avoid doing imports until
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-3-97bf2a96714e> in <module>()
     29 line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
     30                                    interval=50, blit=True)
    ---> 31 line_ani.save('lines.mp4', writer=writer)
     32 
     33 fig2 = plt.figure()

    /anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
       1258                         # TODO: See if turning off blit is really necessary
       1259                         anim._draw_next_frame(d, blit=False)
    -> 1260                     writer.grab_frame(**savefig_kwargs)
       1261 
       1262         # Reconnect signal for first draw if necessary

    /anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
         97                 value = type()
         98             try:
    ---> 99                 self.gen.throw(type, value, traceback)
        100             except StopIteration as exc:
        101                 # Suppress StopIteration *unless* it's the same exception that

    /anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
        235             yield self
        236         finally:
    --> 237             self.finish()
        238 
        239 

    /anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in finish(self)
        367     def finish(self):
        368         '''Finish any processing for writing the movie.'''
    --> 369         self.cleanup()
        370 
        371     def grab_frame(self, **savefig_kwargs):

    /anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in cleanup(self)
        406     def cleanup(self):
        407         '''Clean-up and collect the process used to write the movie file.'''
    --> 408         out, err = self._proc.communicate()
        409         self._frame_sink().close()
        410         verbose.report('MovieWriter -- '
    
    /anaconda3/lib/python3.6/subprocess.py in communicate(self, input, timeout)
        841 
        842             try:
    --> 843                 stdout, stderr = self._communicate(input, endtime, timeout)
        844             finally:
        845                 self._communication_started = True

    /anaconda3/lib/python3.6/subprocess.py in _communicate(self, input, endtime, orig_timeout)
       1503                     selector.register(self.stdin, selectors.EVENT_WRITE)
       1504                 if self.stdout:
    -> 1505                     selector.register(self.stdout, selectors.EVENT_READ)
       1506                 if self.stderr:
       1507                     selector.register(self.stderr, selectors.EVENT_READ)

    /anaconda3/lib/python3.6/selectors.py in register(self, fileobj, events, data)
        349 
        350         def register(self, fileobj, events, data=None):
    --> 351             key = super().register(fileobj, events, data)
        352             poll_events = 0
        353             if events & EVENT_READ:

    /anaconda3/lib/python3.6/selectors.py in register(self, fileobj, events, data)
        235             raise ValueError("Invalid events: {!r}".format(events))
        236 
    --> 237         key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
        238 
        239         if key.fd in self._fd_to_key:

    /anaconda3/lib/python3.6/selectors.py in _fileobj_lookup(self, fileobj)
        222         """
        223         try:
    --> 224             return _fileobj_to_fd(fileobj)
        225         except ValueError:
        226             # Do an exhaustive search.

    /anaconda3/lib/python3.6/selectors.py in _fileobj_to_fd(fileobj)
         37         except (AttributeError, TypeError, ValueError):
         38             raise ValueError("Invalid file object: "
    ---> 39                              "{!r}".format(fileobj)) from None
         40     if fd < 0:
         41         raise ValueError("Invalid file descriptor: {}".format(fd))

    ValueError: Invalid file object: <_io.BufferedReader name=76>

  [1]: https://matplotlib.org/2.1.2/gallery/animation/basic_example_writer_sgskip.html
  [2]: https://jakevdp.github.io/blog/2012/08/18/matplotlib-animation-tutorial/

**Comment by ImportanceOfBeingErnest** [comment]
There is an implicit issue raised within #8760, which is "How do you get a useful log for the call to ffmpeg". Is this solved by #12369? 

@bjce Can you install matplotlib 3.0.1 and see what the error message is then?

**Comment by bjce** [comment]
Thank you very much for rapid answer @ImportanceOfBeingErnest. I just installed matplotlib 3.0.1 and it unfortunately didn't solve the problem. Do you have any idea about what I should do next?

**Comment by ImportanceOfBeingErnest** [comment]
That's what I suspected. What happens if you use a `FFMpegFileWriter` instead of a `FFMpegWriter`, i.e. `writer = FFMpegFileWriter(fps=15, metadata=dict(artist='Me'), bitrate=1800)`? Does the error still occur, or is there a different error message in that case?

**Comment by anntzer** [comment]
@ImportanceOfBeingErnest fwiw #12369 is only in master, not 3.0.1 (but after that PR we should hopefully not get that traceback anymore).

**Comment by bjce** [comment]
Thank you again for your Feedbacks @ImportanceOfBeingErnest and @anntzer. 

So I replaced the line:

```
writer = Writer(fps=15, metadata=dict(artist='Me'), bitrate=1800)
```
by: 
```
writer = FFMpegFileWriter(fps=15, metadata=dict(artist='Me'), bitrate=1800)
```
and got the following error message: 

```
True
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-3d41532c6cc6> in <module>()
     24 Writer = animation.writers['ffmpeg']
     25 # writer = Writer(fps=15, metadata=dict(artist='Me'), bitrate=1800) # line replaced
---> 26 writer = FFMpegFileWriter(fps=15, metadata=dict(artist='Me'), bitrate=1800)
     27 
     28 fig1 = plt.figure()

NameError: name 'FFMpegFileWriter' is not defined
```
I then replaced the same line by: 

```
writer = animation.FFMpegFileWriter(fps=15, metadata=dict(artist='Me'), bitrate=1800)
```
and got the following error message:
```
True
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
    229         try:
--> 230             yield self
    231         finally:

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1173                         anim._draw_next_frame(d, blit=False)
-> 1174                     writer.grab_frame(**savefig_kwargs)
   1175 

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in grab_frame(self, **savefig_kwargs)
    507             # frame format and dpi.
--> 508             with self._frame_sink() as myframesink:
    509                 self.fig.savefig(myframesink, format=self.frame_format,

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in _frame_sink(self)
    494         # because it will no longer be referenced and will be gc-ed.
--> 495         return open(fname, 'wb')
    496 

PermissionError: [Errno 13] Permission denied: '_tmp0000000.png'

During handling of the above exception, another exception occurred:

PermissionError                           Traceback (most recent call last)
<ipython-input-6-e3af5bbbe0b8> in <module>()
     36 line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
     37                                interval=50, blit=True)
---> 38 line_ani.save('lines.mp4', writer=writer)
     39 
     40 fig2 = plt.figure()

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1172                         # TODO: See if turning off blit is really necessary
   1173                         anim._draw_next_frame(d, blit=False)
-> 1174                     writer.grab_frame(**savefig_kwargs)
   1175 
   1176         # Reconnect signal for first draw if necessary

/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
    230             yield self
    231         finally:
--> 232             self.finish()
    233 
    234 

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in finish(self)
    519         # are available to be assembled.
    520         self._run()
--> 521         MovieWriter.finish(self)  # Will call clean-up
    522 
    523         # Check error code for creating file here, since we just run

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in finish(self)
    356     def finish(self):
    357         '''Finish any processing for writing the movie.'''
--> 358         self.cleanup()
    359 
    360     def grab_frame(self, **savefig_kwargs):

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in cleanup(self)
    535 
    536     def cleanup(self):
--> 537         MovieWriter.cleanup(self)
    538 
    539         # Delete temporary files

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in cleanup(self)
    394         '''Clean-up and collect the process used to write the movie file.'''
    395         out, err = self._proc.communicate()
--> 396         self._frame_sink().close()
    397         _log.debug('MovieWriter -- Command stdout:\n%s', out)
    398         _log.debug('MovieWriter -- Command stderr:\n%s', err)

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in _frame_sink(self)
    493         # This file returned here will be closed once it's used by savefig()
    494         # because it will no longer be referenced and will be gc-ed.
--> 495         return open(fname, 'wb')
    496 
    497     def grab_frame(self, **savefig_kwargs):

PermissionError: [Errno 13] Permission denied: '_tmp0000001.png'
```
Does that help?

**Comment by ImportanceOfBeingErnest** [comment]
No, the problem will still be there, even with the new error message system. You could just hope to get a more useful error message then. As to why you don't have permission on that file I don't know.

**Comment by bjce** [comment]
thank you for your answer @ImportanceOfBeingErnest. So as I'm not a programmer and I'm not very used to github, what do you think is the next step?

**Comment by bjce** [comment]
ok so I didn't find any file names "_tmp0000001.png" in my harddisk

I then changed the last line of code from `im_ani.save('im.mp4', writer=writer)`
to `im_ani.save('/Users/mymac/Documents/Github/matplotlib/im.mp4', writer=writer)`
(in order to save the file in a folder that I could look at and not a random one) and I got:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-93940c9fdc71> in <module>()
     36 line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
     37                                interval=50, blit=True)
---> 38 line_ani.save('lines.mp4', writer=writer)
     39 
     40 fig2 = plt.figure()

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1172                         # TODO: See if turning off blit is really necessary
   1173                         anim._draw_next_frame(d, blit=False)
-> 1174                     writer.grab_frame(**savefig_kwargs)
   1175 
   1176         # Reconnect signal for first draw if necessary

/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     86         if type is None:
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:
     90                 return False

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
    230             yield self
    231         finally:
--> 232             self.finish()
    233 
    234 

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in finish(self)
    532                 pass
    533             raise RuntimeError('Error creating movie, return code: {}'
--> 534                                .format(self._proc.returncode))
    535 
    536     def cleanup(self):

RuntimeError: Error creating movie, return code: -6
[ ]

​```

**Comment by bjce** [comment]
@anntzer regarding you first question: I could save a plot without problem in that same directory with the following command: 

```
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
 
y = [2,4,6,8,10,12,14,16,18,20]
x = np.arange(10)
fig = plt.figure()
ax = plt.subplot(111)
ax.plot(x, y, label='$y = numbers')
plt.title('Legend inside')
ax.legend()
# plt.show()
 
fig.savefig('/Users/mymac/Documents/Github/matplotlib/plot.png')
```

**Comment by anntzer** [comment]
May be easier to debug in the yet-to-be-released 3.1, but other than that I don't have any idea right now.

**Comment by jklymak** [comment]
Just to be clear the backtrace above does not match the code.

**Comment by jklymak** [comment]
@bjce: Its your traceback 4 that doesn't match the code...  Thanks

**Comment by bjce** [comment]
thank you for your comment @jklymak . So I'm sorry if I'm overflowing this issue with too many codes and tracebacks but just to make it clear, I'm copying again the code I'm talking about with the corresponding traceback: 

```
import numpy as np
import matplotlib
matplotlib.use("Agg")

import logging
logger = logging.getLogger('matplotlib')
logger.setLevel(logging.INFO)

import matplotlib.pyplot as plt
import matplotlib.animation as animation

# Check condition from matplotlib.animation source which if true will disable ffmpeg logging:
print(animation._log.getEffectiveLevel() > logging.DEBUG) # prints False

def update_line(num, data, line):
    line.set_data(data[..., :num])
    return line,

# Fixing random state for reproducibility
np.random.seed(19680801)


# Set up formatting for the movie files
Writer = animation.writers['ffmpeg']
# writer = Writer(fps=15, metadata=dict(artist='Me'), bitrate=1800)
writer = animation.FFMpegFileWriter(fps=15, metadata=dict(artist='Me'), bitrate=1800)

fig1 = plt.figure()

data = np.random.rand(2, 25)
l, = plt.plot([], [], 'r-')
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.xlabel('x')
plt.title('test')
line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
                               interval=50, blit=True)
line_ani.save('/Users/mymac/Documents/Github/matplotlib/lines.mp4', writer=writer)

fig2 = plt.figure()

x = np.arange(-9, 10)
y = np.arange(-9, 10).reshape(-1, 1)
base = np.hypot(x, y)
ims = []
for add in np.arange(15):
    ims.append((plt.pcolor(x, y, base + add, norm=plt.Normalize(0, 30)),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                               blit=True)
im_ani.save('/Users/mymac/Documents/Github/matplotlib/im.mp4', writer=writer)
```
**traceback N°5**: 

```
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: matplotlib.pyplot as already been imported, this call will have no effect.
  This is separate from the ipykernel package so we can avoid doing imports until
True
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-da5aa52a8c13> in <module>()
     36 line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
     37                                interval=50, blit=True)
---> 38 line_ani.save('/Users/mymac/Documents/Github/matplotlib/lines.mp4', writer=writer)
     39 
     40 fig2 = plt.figure()

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in save(self, filename, writer, fps, dpi, codec, bitrate, extra_args, metadata, extra_anim, savefig_kwargs)
   1172                         # TODO: See if turning off blit is really necessary
   1173                         anim._draw_next_frame(d, blit=False)
-> 1174                     writer.grab_frame(**savefig_kwargs)
   1175 
   1176         # Reconnect signal for first draw if necessary

/anaconda3/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     86         if type is None:
     87             try:
---> 88                 next(self.gen)
     89             except StopIteration:
     90                 return False

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in saving(self, fig, outfile, dpi, *args, **kwargs)
    230             yield self
    231         finally:
--> 232             self.finish()
    233 
    234 

/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py in finish(self)
    532                 pass
    533             raise RuntimeError('Error creating movie, return code: {}'
--> 534                                .format(self._proc.returncode))
    535 
    536     def cleanup(self):

RuntimeError: Error creating movie, return code: -6
```

**Comment by bjce** [comment]
@jklymak Here is the traceback from command line

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 1174, in save
    writer.grab_frame(**savefig_kwargs)
  File "/anaconda3/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/anaconda3/lib/python3.6/site-packages/matplotlib/animation.py", line 534, in finish
    .format(self._proc.returncode))
RuntimeError: Error creating movie, return code: -6
```

**Comment by akanksha95** [comment]
Did you find a solution for this? I am getting similar errors with FFMpegWriter and FFMpegFileWriter.

**Comment by bjce** [comment]
hello @akanksha95. What I finally did is that I created an animation with FFMpeg (after having created all the single images with matplotlib) directly from the Terminal using [this code](https://stackoverflow.com/questions/53836568/how-to-create-a-video-from-images-on-a-tif-format-with-ffmpeg). Hope it helps

**Comment by bjce** [comment]
@akanksha95 : i posted a question on [stackoverflow](https://stackoverflow.com/questions/53198609/trying-to-save-an-animated-of-graph-with-matplotlib-in-python-invalid-file-ob/54263809#54263809) and got code as an answer that works well. Here is the code: 

```
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 20 22:19:44 2018

@author: Irbin
"""

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.animation as animation
plt.rcParams['animation.ffmpeg_path'] = '/usr/local/bin/ffmpeg' # Add the path of ffmpeg here!!

def update_line(num, data, line):
    line.set_data(data[..., :num])
    return line,

# Fixing random state for reproducibility
np.random.seed(19680801)


# Set up formatting for the movie files
Writer = animation.writers['ffmpeg']
writer = Writer(fps=15, metadata=dict(artist='Me'), bitrate=1800)


fig1 = plt.figure()

data = np.random.rand(2, 25)
l, = plt.plot([], [], 'r-')
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.xlabel('x')
plt.title('test')
line_ani = animation.FuncAnimation(fig1, update_line, 25, fargs=(data, l),
                                   interval=50, blit=True)
line_ani.save('lines.mp4', writer=writer)

fig2 = plt.figure()

x = np.arange(-9, 10)
y = np.arange(-9, 10).reshape(-1, 1)
base = np.hypot(x, y)
ims = []
for add in np.arange(15):
    ims.append((plt.pcolor(x, y, base + add, norm=plt.Normalize(0, 30)),))

im_ani = animation.ArtistAnimation(fig2, ims, interval=50, repeat_delay=3000,
                                   blit=True)
im_ani.save('im.mp4', writer=writer)
```

**Comment by Winsonguo** [comment]
@bjce  Thanks, your solution works for me.

**Comment by Simshang** [comment]
In my problem, I rebuild ffmpeg with `--enable protocols`
