### ISSUE TITLE
3D bar chart with shading is rendered incorrectly

### ISSUE THREAD

**Issue by sazas** [matplotlib/matplotlib#13728]
### Bug report

**Bug summary**
Z-order of rendered planes in 3d bar chart produced by bar3d is wrong. It is seen even in the example here https://matplotlib.org/gallery/mplot3d/3d_bars.html. One of the bars (at location 2, 4, height 6) is drawn on top of the highest bar, even though it supposed to be behind it.

**Code for reproduction**
A small modification of the code from example to make it more pronounced.
```python
import numpy as np
import matplotlib.pyplot as plt
# This import registers the 3D projection, but is otherwise unused.
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import


# setup the figure and axes
fig = plt.figure(figsize=(8, 8))
ax1 = fig.add_subplot(111, projection='3d')

# fake data
_x = np.arange(8)
_y = np.arange(8)
_xx, _yy = np.meshgrid(_x, _y)
x, y = _xx.ravel(), _yy.ravel()

top = x + y
bottom = np.zeros_like(top)
width = depth = 1

ax1.bar3d(x, y, bottom, width, depth, top, shade=True)
ax1.set_title('Shaded')
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/9054941/54744129-1905ce80-4c01-11e9-808a-39a54d870363.png)

Everything to the right from diagonal is rendered incorrectly.

**Matplotlib version**
Tested on two machines with the same results.
  * Operating system: mac and windows
  * Matplotlib version:
 matplotlib                2.1.2            py36h6d6146d_0
and
 matplotlib                3.0.3            py37_0    conda-forge
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version:
3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
and
3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 13:32:59) [MSC v.1900 64 bit (AMD64)]
  * Jupyter version (if applicable):
ipython                   5.1.0                    py36_1
and
ipython                   7.3.0            py37h39e3cac_0    conda-forge

**Comment by ImportanceOfBeingErnest** [comment]
There is clearly room for improvement, this would be the place to start:

https://github.com/matplotlib/matplotlib/blob/9faf2313cf0e37a6b01ad691b8a430eb2b4ebe3f/lib/mpl_toolkits/mplot3d/art3d.py#L705-L710

**Comment by seongminnpark** [comment]
Setting `zsort` to `'min` in `bar3d` (`ax1.bar3d(x, y, bottom, width, depth, top, shade=True, zsort='min')`) seems to take care of the overlap order problem in the example case and the tutorial case.

However, this only works because the examples are drawing uniformly shaped bars, and the object with the smaller minimum z coordinate is guaranteed to be at the front. 
 
@ImportanceOfBeingErnest Im curious: is there a reasoning behind default `zsort` being `average`? Would it be better if it is changed to `min`? Neither approach is perfect but more use cases might benefit from default `zsort` being `min`.

**Comment by dstansby** [comment]
I think this is fixed, the outcome of the code above on the master branch is now:
![Figure_1](https://user-images.githubusercontent.com/6197628/63094986-ebc80d00-bf61-11e9-8984-1adb408ad015.png)

**Comment by ImportanceOfBeingErnest** [comment]
That image shows the same problem as the one from the original post. So, no it's not fixed. 

Since neither `min` nor `average` give in general good visuals, I don't think it makes sense to exchange one for the other. 

A possible intermediate solution is to take user-defined plot orders, as in https://github.com/matplotlib/matplotlib/pull/14508 or #12744 also for the Poly3DCollection.

**Comment by oscargus** [comment]
Since there is a recent PR for this, it makes sense to keep it.
