### ISSUE TITLE
imshow pixel boundaries wrong when zoomed in

### ISSUE THREAD

**Issue by plisdku** [matplotlib/matplotlib#14143]
### Bug report

**Bug summary**

`imshow` pixel boundaries visibly shift from expected coordinates by many pixels when zooming in, depending on dpi but not improving at high dpi.

I am trying to plot gridded data with `imshow` so it aligns with other plot elements like lines.  When I zoom in on the image so image pixels are bigger than the plot axes, the boundaries between pixels are visibly shifted from where they ought to be.  The shift depends on the dpi of the figure but cannot be resolved by changing the dpi.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

dpi=72
plt.figure(figsize=(12,4), dpi=dpi)
z = np.eye(2)
for ii, d in enumerate([1, .1, .01]):
    plt.subplot(1,3,ii+1)
    plt.imshow(z)
    plt.xlim([0.5-d, 0.5+d])
    plt.ylim([0.5-d, 0.5+d])
    plt.vlines([-.5, 0.5, 1.5, 2.5, 3.5], -.5, 3.5, 'r')
    plt.hlines([-.5, 0.5, 1.5, 2.5, 3.5], -.5, 3.5, 'r')
    plt.title([f"Full image ({dpi} dpi)", "10x", "100x"][ii])
```

**Actual outcome**

Several results with different dpi.  Screenshotted at same resolution because one of them was generated at 1000 dpi.

![image](https://user-images.githubusercontent.com/6510640/57245289-51197300-6fef-11e9-96d9-d3ffbbf6e327.png)

**Expected outcome**

The red grid lines drawn with `vlines` and `hlines` should lie directly on pixel boundaries.

**Matplotlib version**

Mac OS X 10.12.6 

Matplotlib version 3.0.3 installed from pip I think.
Backend: module://ipykernel.pylab.backend_inline

Python 3.7

**Comment by jklymak** [comment]
Does `dpi=1000` really change the dpi in the inline backend?

**Comment by plisdku** [comment]
It definitely gave me an enorrrrrrrmous png file, I can attest to that.  :-)  I don't know how mpl is working on the inside though.

**Comment by jklymak** [comment]
Yes, I agree, that certainly is a bug...  Thanks for the good report.

**Comment by tacaswell** [comment]
This is yet more issues with your favorite part of the code base @jklymak (`AxesImage` ;) )

I think this is a duplicate of https://github.com/matplotlib/matplotlib/issues/1441 I still think the issue is that we are doing the re-sampling from the full input data -> the screen.  If you zoom way in / turn up the DPI, we start to get numerical issues mapping back from screen space to input space.  

Put another way, when you are very zoomed in we are pulling a 200 x 200 window out of a 200k x 200k notional array and the error on picking the right place to transition from input pixel A to pixel B should be evaluated against the 200K space.

**Comment by adeak** [comment]
I'm _pretty_ sure this is the same issue, but I can see the same bug even without zooming in with this gridded example (on a TkAgg backend in case it matters):
```python
import matplotlib.pyplot as plt

fig,ax = plt.subplots() 
N = 12 
ax.imshow(np.random.rand(N, N)) 
seps = np.arange(-0.5, N) 
ax.vlines(seps, -0.5, N - 0.5, linewidth=1)
ax.hlines(seps, -0.5, N - 0.5, linewidth=1)
plt.show()
```
![mpl_imshow_grid_bug](https://user-images.githubusercontent.com/17914410/74275565-60fb7b80-4d14-11ea-8c8a-398cac4792a0.png)
Note the bunch of yellow and brighter green pixels that stretch over the grid lines.

The key difference with respect to the original example in the issue is probably that the thinner grid lines that I use no longer hide the misalignment. Just like in [the suspected duplicate](https://github.com/matplotlib/matplotlib/issues/1441#issuecomment-331746665) some of the overlaps jump around if I pan interactively, but this is not very obvious because most of the overlaps are pretty resilient to panning and only disappear in a narrow window during panning.

**Comment by adeak** [comment]
The code block from my previous comment still shows the bug on v3.10.5 (with qtagg backend here):

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/c15b2e98-7ff8-49bd-b9b5-8022a371d6a8" />

This should stay open.

**Comment by dscontract** [comment]
Hello, @plisdku
I am using the design by contract methodology to create tentative correct programs, taking the bug description as requirements (such as what not to do) and then generating patched code that fulfills those requirements. Can you kindly try the following code and let me know if it resolves the issue? Thank you!

Added an explicit `extent` to align pixel edges with grid lines and disabled resampling (`interpolation='none', resample=False`) to avoid dpi-dependent shifts.  


```python
import numpy as np
import matplotlib.pyplot as plt

dpi = 72
plt.figure(figsize=(12, 4), dpi=dpi)
z = np.eye(2)

# Define the exact pixel-edge extent for the image so that integer+0.5 lines
# coincide with pixel boundaries, and disable resampling to avoid dpi-dependent shifts.
extent = (-0.5, z.shape[1] - 0.5, -0.5, z.shape[0] - 0.5)

for ii, d in enumerate([1, 0.1, 0.01]):
    ax = plt.subplot(1, 3, ii + 1)
    ax.imshow(z, origin='lower', interpolation='none', resample=False, extent=extent)
    ax.set_xlim([0.5 - d, 0.5 + d])
    ax.set_ylim([0.5 - d, 0.5 + d])
    ax.vlines([-.5, 0.5, 1.5, 2.5, 3.5], -.5, 3.5, 'r')
    ax.hlines([-.5, 0.5, 1.5, 2.5, 3.5], -.5, 3.5, 'r')
    ax.set_title([f"Full image ({dpi} dpi)", "10x", "100x"][ii])
```

**Comment by QuLogic** [comment]
This should be fixed by #30184.

**Comment by adeak** [comment]
@QuLogic I'm not completely sure that I'm testing it right but I think the bug in my last comment is still present on `main`. I couldn't get an editable install to work right now, so I ended up just installing current `main` from github directly (plus PyQt6). I see this:
```python
import matplotlib.pyplot as plt
import numpy as np

fig,ax = plt.subplots() 
N = 12 
ax.imshow(np.random.rand(N, N)) 
seps = np.arange(-0.5, N) 
ax.vlines(seps, -0.5, N - 0.5, linewidth=1)
ax.hlines(seps, -0.5, N - 0.5, linewidth=1)
plt.show()
```

<img width="639" height="560" alt="Image" src="https://github.com/user-attachments/assets/a387d152-53c6-4d9b-a75d-fd19f2f54bcd" />

The grid issue is still there. And I _think_ I'm correctly on `main`:
```python
>>> import matplotlib
>>> matplotlib.__version__
'3.11.0.dev1652+gddd4196c7'
```
as newest commit on `main` currently is https://github.com/matplotlib/matplotlib/commit/ddd4196c7192a80846c1fd4fcb721bc849d8e0bc.

**Comment by QuLogic** [comment]
Your example is different from the original issue as it very much has to do with zooming. Perhaps @ayshih has some ideas on yours.

**Comment by ayshih** [comment]
@adeak: Argh, you are correct that your issue has not been fixed.  I've re-confirmed that #30184 fixed the original issue, but I apparently overlooked checking your example too.  I'll look into it.

**Comment by adeak** [comment]
Sorry @ayshih 😅 For what it's worth this is not an issue for me today, I found this 6 years ago. So if this is a different problem we can open a dedicated issue to track it and you need not jump into it just for my sake ;)

**Comment by ayshih** [comment]
@adeak: Based on my investigation so far, the problem in your example is indeed distinct from the original issue, and it is very important to fix.  It's not a bug internal to the image-resampling code, but rather it has to do with how image placement affects what resampling is requested and how the resampled image is drawn.  Can you create a dedicated issue?

**Comment by adeak** [comment]
Sure thing @ayshih, thanks for looking into this.
