### ISSUE TITLE
a bug that latex expression with subscripts exceeds bbox 

### ISSUE THREAD

**Issue by qm1900** [matplotlib/matplotlib#14177]
### Bug report

the background box for a text object that is composed via latex with subscript can not be covered by the box if letting the padding of the box be equal to 0

```python
# Paste your code here
#
#
ax.annotate(r'$A_{\tiny 1}$', xy=(0.5,0.5), bbox=dict(boxstyle='round,pad=0', fc='w', ec='none'))
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
### Example

~~~
import matplotlib.pyplot as plt

kw = dict(
    fontsize=40,
    bbox=dict(boxstyle='round,pad=0', fc='lightsteelblue', ec='none')
)

plt.axhline(y=0.7)
plt.annotate('A', xy=(0.3, 0.7), **kw)
plt.annotate(r'$A$', xy=(0.4, 0.7), **kw)
plt.annotate(r'$A_{\tiny 1}$', xy=(0.5, 0.7), **kw)
plt.annotate(r'$A_{\tiny 1j}$', xy=(0.65, 0.7), **kw)

plt.axhline(y=0.4)
plt.annotate('A', xy=(0.3, 0.4), va='bottom', **kw)
plt.annotate(r'$A$', xy=(0.4, 0.4), va='bottom', **kw)
plt.annotate(r'$A_{1}$', xy=(0.5, 0.4), va='bottom', **kw)
plt.annotate(r'$A_{1j}$', xy=(0.65, 0.4), va='bottom', **kw)
~~~

![grafik](https://user-images.githubusercontent.com/2836374/57571863-7a813700-7413-11e9-9b62-ede08a5b9f59.png)


### Observations
- Having subscripts in LaTeX shifts the text upwards, but doesn't change the size of the bbox.
- Interestingly though, the box gets higher, if I use `1j` instead of `1` as a subscript.
- Verticalalignment (bottom or baseline (the default)) results in the same positioning of the box, no matter what text is used.

**Comment by anntzer** [comment]
@timhoffm's example now gives
![test](https://user-images.githubusercontent.com/1322974/119263177-46ce6f80-bbde-11eb-9e37-f1bb4c0f2220.png)
so it seems like the baseline case has been fixed (possibly by https://github.com/matplotlib/matplotlib/pull/16476).  The "bottom" alignment case remains, but I suspect that can be fixed "relatively" easily because the dvi parser knows the descent of each glyph, so should be able to return the text's bbox.

**Comment by timhoffm** [comment]
Except for $A_1$ all examples still appear to be shifted by 1px upwards.

![grafik](https://user-images.githubusercontent.com/2836374/119282627-aa868600-bc3a-11eb-861d-59394556135e.png)

**Comment by anntzer** [comment]
My (non-verified) guess is that the 1px shift is related to the "wiggly baseline" mentioned in https://github.com/matplotlib/matplotlib/pull/5414, which basically arises because mathtext/usetex texts (which are basically prerendered as bitmaps first) use their top-right corner as reference point, but there's some rounding associated with it if the text object gets antialiased past the top limit, which (handwavingly) leads to the baseline wiggling; instead, these bitmaps should use the baseline as reference y to avoid the problem.

**Comment by kc9jud** [comment]
This still seems to be a problem with more complex situations:

```python3
import matplotlib.pyplot as plt

kw = dict(
    usetex=True,
    fontsize=40,
    bbox=dict(boxstyle='round,pad=0', fc='lightsteelblue', ec='none')
)

plt.axhline(y=0.7)
plt.annotate('A \n B', xy=(0.4, 0.7), **kw)
plt.annotate(r'$A$' ' \n ' r'$B$', xy=(0.5, 0.7), **kw)
plt.annotate(r'$A_{\tiny 1}$' ' \n ' r'$B_{\tiny 1}$', xy=(0.6, 0.7), **kw)
plt.annotate(r'$A_{\tiny 1j}$' ' \n ' r'$A_{\tiny 1j}$', xy=(0.8, 0.7), **kw)

plt.axhline(y=0.3)
plt.annotate('A \n B', xy=(0.4, 0.3), va='bottom', **kw)
plt.annotate(r'$A$' ' \n ' r'$B$', xy=(0.5, 0.3), va='bottom', **kw)
plt.annotate(r'$A_{1}$' ' \n ' r'$B_{\tiny 1}$', xy=(0.6, 0.3), va='bottom', **kw)
plt.annotate(r'$A_{1j}$' ' \n ' r'$A_{\tiny 1j}$', xy=(0.8, 0.3), va='bottom', **kw)

plt.annotate(r'$^6\mathrm{He}$ $0^+$' ' \n ' r'$n0p_{3/2}$', xy=(0.05, 0.3), va='bottom', **kw)

plt.show()
```

gives:
![Figure_1](https://user-images.githubusercontent.com/4133644/142036974-0f21340c-fd9d-42f7-96b3-3633cc303dab.png)

**Comment by kc9jud** [comment]
This looks to be an issue with superscripts -- I will open a new issue.

**Comment by jklymak** [comment]
Your example is helpful.  Maybe add to #7075 which I think is the same thing (if more convoluted)

**Comment by anntzer** [comment]
Haven't checked but almost likely still valid as no work has been done on these aspects, and will likely be stalled until the image comparison framework is fixed as any change to the wiggly baselines will involve regen'ing many, many reference images.

**Comment by QuLogic** [comment]
The wiggly baseline should be fixed by #30059; does it also fix the bbox issue originally reported?

**Comment by anntzer** [comment]
The non-mathtext "A" is also properly aligned at the top now (with or without #30059); the second and fourth cases of the first line still appear one pixel too high:
<img width="627" height="390" alt="Image" src="https://github.com/user-attachments/assets/db787e19-1917-4499-907f-e9775f9bd7c6" />
My (rather uncertain) guess is that this is related to the precision of the tfm metrics and I had suggested a fix at https://github.com/matplotlib/matplotlib/issues/21653#issuecomment-971886968 (but that'd require a bit of work).

On the other hand we should probably also try to get something like https://github.com/matplotlib/matplotlib/issues/21653#issuecomment-970660924 into the text-overhaul branch, I think?

**Comment by tacaswell** [comment]
This is what I get with current main, I am going to make the call that this is close enough:

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/5b0e4d28-ee4a-4caa-bacc-f95a779c79ba" />
