### ISSUE TITLE
Misalignment imshow vs. grid lines

### ISSUE THREAD

**Issue by rougier** [matplotlib/matplotlib#1441]
The following script show a mis-alignment between grid lines and image patterns while they should be aligned:

``` python
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

n = 16
fig = plt.figure(figsize=(6,6))
Z = np.zeros((n,n))
Z[::2,::2] = Z[1::2,1::2] = 1
plt.imshow(Z, interpolation='none', cmap=plt.cm.gray, extent=[0,n,0,n], alpha=0.25)
plt.xticks(np.arange(0,n), []), plt.yticks(np.arange(0,n), [])
plt.grid(ls='solid')
delta = 0.01
plt.xlim(1-delta,1+delta), plt.ylim(1-delta,1+delta)
plt.savefig('pylab-grid.png')
plt.savefig('pylab-grid.pdf')
```

**Comment by jkseppan** [comment]
If I change `interpolation='none'` to `interpolation='nearest'` the PDF looks similar to the PNG. The Agg backend has to resample images to display them, but the PDF backend does not, so when you make a very low-resolution image it's up to the viewer program to figure out how to display it.

Here's another example adapted from #2935:

```
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['pdf.compression'] = 0

plt.gcf().set_size_inches([1,1])
a=np.bitwise_xor.outer(np.arange(20)&2, np.arange(20)&2)
im = plt.imshow(a, interpolation='none', cmap='gray', origin='lower', extent=[-2,2,-2,2])
plt.gca().set_xticks(np.linspace(-2,2,21))
plt.gca().set_yticks(np.linspace(-2,2,21))
plt.gca().xaxis.set_ticklabels([])
plt.gca().yaxis.set_ticklabels([])
plt.grid(ls='-',lw=0.1,color='white')
plt.axis('square')
plt.savefig('pattern.png')
plt.savefig('pattern.pdf')
```

Here's what the checkerboard pattern image looks, as written in the PDF file:

```
ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00
ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00
00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fe
00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff ff
fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 00
ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00
00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fe
00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff ff
fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 00
ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00
00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fe
00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff ff
fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 00
ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00
00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fe
00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff ff
fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 00
ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00
00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fc 00 01 fe fe
00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff fe 00 00 ff ff
```

Note that the values are not all 00 or ff. Even with `interpolation='none'` there is some resampling going on, and the data written in the file is not exactly what was given to imshow.

**Comment by efiring** [comment]
The bug is still present after the image refactor.

**Comment by tacaswell** [comment]
There is some quantization going on with this.  If you pan left and right the pattern 'jumps' but the grid lines move smoothly.

**Comment by kuzand** [comment]
The grid lines are misaligned on the x-axis:

> import numpy as np
> import matplotlib.pyplot as plt
> nx, ny = 5, 5
> Z = np.random.randint(2, size=(ny,nx))
> fix, ax = plt.subplots()
> ax.set_xticks(np.arange(0.5, nx-1, 1))
> ax.set_yticks(np.arange(0.5, ny-1, 1))
> plt.imshow(Z, cmap='binary')
> plt.grid()
> plt.show()

**Comment by tacaswell** [comment]
I sunk the better part of a day into this and still don't really understand it (but I as a side-effect, I think I have the start of a performance-improvement PR!).

 - single pixel offset an 'zoomed' out maybe due to implicit pixel snapping on the image, explicit pixel snapping on the grid lines, and a mis-match between the number of pixels in the output and and the number of pixel in the input.   If you ask for a 5x5 gird rendered into 333 pixels across, the 'logical pixels' will not be the same size in 'screen pixels' 
 - if you zoom very far in (like `ax.set_xlim((3.4904144000410406, 3.516563080023857))`) then you can get really big offsets in screen space between the lines and the 'logical pixel' edges, however if you scan the limits slightly left or right the amount of error changes.  As mentioned above, the grid lines move smoothly, the 'logical pixels' jump. This makes me think that we are running into precision issues someplace, but not clear to me where
 - they don't jump in the y-direction, but gets a bit funny with zoom
 - may depend on where in the image you are
 - the error does not depend on figure size, just the x-limits
 - not clear if the issue as at the 'resample the image' step or the 'put the image on the canvas' step.


I _suspect_ that the issue is in how we are calling the Agg resample code, but that may just me blaming the part of the code I understand the least.

**Comment by QuLogic** [comment]
This is about PNG, not PDF, but I wonder if your trawling into raster image rendering might give you some ideas about this, @brunobeltran.

**Comment by brunobeltran** [comment]
Oh neat, this is the error I alluded to in #6827. This is separate from all DPI-related issues actually, and has to do instead with the logic in the helper function `_ImageBase._make_image` that decides how to color each pixel. It will always be off by exactly one-half "input pixels", since it's passed the `_ImageBase`'s `extents`, which look like:

```
    def get_extent(self):
        """Return the image extent as tuple (left, right, bottom, top)."""
        numrows, numcols = self.get_size()
        return (-0.5 + self.ox, numcols-0.5 + self.ox,
                -0.5 + self.oy, numrows-0.5 + self.oy)
```

After I push working versions of the rounding fixes, I'll try to think harder about the "correct" way to fix this. 

This is related to the issue brought up by @efiring yesterday on the call, where we sometimes want to use the center of the pixel's color to decide the color, and sometimes we want the color on the edge...

**Comment by brunobeltran** [comment]
If anyone has thoughts about how this should be fixed, the easiest way to see the faulty logic is to use a trivial example:

```
matplotlib.rcParams['figure.dpi'] = 100
delta = 0.01

plt.imshow([[1, 0], [0, 1]], interpolation='antialiased')
plt.xlim([1/2 - delta, 1/2 + delta])
plt.ylim([1/2 - delta, 1/2 + delta])
```

and set a breakpoint at `image.py:903` or so. Notice that the input array is correct, but the return value from `make_image` already has the "offset" issue, due to the value passed to `bbox`.

**Comment by oscargus** [comment]
Still a problem, this is the current PNG from the first example:

![pylab-grid](https://user-images.githubusercontent.com/8114497/221842993-5a4e9d29-9e02-45af-9924-439aa737bbfd.png)

**Comment by pelson** [comment]
Just to add that this issue still exists on main, and I can confirm that it can be seen without the Agg renderer (cairo & another). This supports the assumption that this is a problem in the image code, rather than the renderer.

I find it curious that you only see the misalignment in the y-axis, and not in the x.

**Comment by timhoffm** [comment]
This should stay open.

**Comment by QuLogic** [comment]
This should be fixed by #30184.
