### ISSUE TITLE
common_texification misses & (ampersand)

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#15493]
```python
from matplotlib.backends.backend_pgf import common_texification

print(common_texification("cats & dogs"))
```
```
cats & dogs
```
Expected:
```
cats \& dogs
```

**Comment by anntzer** [comment]
What exactly are you trying to achieve?  (Pretend that common_texification is private, which it should be.  Is this bug observable without directly calling it?)

Note that independently of pgf, something like
```
text(.5, .5, "cats & dogs", usetex=True)
```
already fails with
```
! Misplaced alignment tab character &.
l.14 ...ize{10.000000}{12.500000}{\sffamily cats &
                                                   dogs}
```
and the pgf backend effectively operates as if usetex=True.

**Comment by nschloe** [comment]
> What exactly are you trying to achieve?

I'm using it in tikzplotlib, https://github.com/nschloe/tikzplotlib/blob/e44a75c6acd4bec6d6ff8a2dd805b86f51e1918d/tikzplotlib/_axes.py#L10, to replicate titles in labels in TeX.

**Comment by anntzer** [comment]
I'm not really convinced this should be fixed on mpl's side (basically, the question, as above, is whether `text(.5, .5, "cats & dogs")` (or indeed using any other tex-special character) should work when using the pgf backend).

**Comment by timhoffm** [comment]
1. `common_texification()` should be made private. This is intended for internal use only.
2. I'm not sure if it's actually doing the right thing. It is used in `RendererPgf.draw_text()` and in `RendererPgf.get_text_width_height_descent()` to preprocess the passed text string. See #16900 for a description.

   Some random thoughts:
   - I think the wrapping of math expressions is right.
   - Should there be any escaping in text-mode?
     - This may cause unwanted escapes when you want to have TeX expressions in the text.
     - Currently escaped special characters:
       - `_` and `^` are only valid in math mode. At least there's no conflict of semantics if we escape them in texts.
       - `%` is the comment sign. I wouldn't expect comments in passed strings, so it may be ok to escape it.
       - `$` should not appear unescaped in text mode because it's the split marker for math-mode. There's no need to escape it (but no harm either).
     - Currently *not* escaped special characters:
       - `{}` may well be used in a tex command within the text mode. Should not be escaped.
       - `#` and `&`: not sure if there are tex comands which could make use of them.
     - I didn't check further, but https://github.com/matplotlib/matplotlib/issues/15493#issuecomment-547342287 indicates, that some of the chars wouldn't even make it down to the renderer call.
     - Overall, we may escape some characters; but we cannot escape all characters. Is it convenient to auto-escape if possible or is it rather confusing that some chars are escaped, others are not?

**Comment by chernikovmaksim** [comment]
Hello, unfortunately, I discovered that this problem still exists.

```
ValueError: Error measuring '\\sffamily\\fontsize{10.000000}{12.000000}\\selectfont Something & Something'
LaTeX Output:
! Misplaced alignment tab character &.
<argument> ...0}{12.000000}\selectfont Something &
                                                   Something
<*> ...2.000000}\selectfont Something & Something}
                                                  \typeout{\the\wd0,\the\ht0...
No pages of output.
Transcript written on texput.log.
```

Code example:

```
import numpy as np
import matplotlib.pyplot as plt
import math

def figsize(wcm,hcm): plt.figure(figsize=(wcm/2.54,hcm/2.54))
figsize(13,9)

x = np.linspace(0,2*math.pi,100)
y = np.sin(x)
plt.plot(x,y,'-')
plt.xlabel("Something & Something")
plt.savefig('test.pdf', backend="pgf")
```

**Comment by anntzer** [comment]
I agree that we should *not* escape `&` and `#` by default because they can appear in legitimate tex strings that you actually want to use (e.g., tabular environments).  (On the other hand, escaping `%^_` is certainly reasonable; note that we already escape `_` in normal usetex texts)  I think we should just document how to force TeX to treat them as normal characters, which is to do
```python
rcParams["pgf.preamble"] = r"\AtBeginDocument{\catcode`\&=12\catcode`\#=12}"
```
Test e.g. with
```python
rcParams["pgf.preamble"] = r"\AtBeginDocument{\catcode`\&=12\catcode`\#=12}"
figtext(.5, .5, "foo &# bar")
savefig("/tmp/test.pdf", backend="pgf")
```

**Comment by chernikovmaksim** [comment]
I seems like the best way. Thank you very much.
