### ISSUE TITLE
plt.imshow: clip_on=False has no effect

### ISSUE THREAD

**Issue by Tal-Golan** [matplotlib/matplotlib#15546]
### Bug report

**Bug summary**

Images plotted by plt.imshow are always clipped, reglardless of the clip_on argument.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.cbook import get_sample_data

fig = plt.figure(figsize=(10,5))
ax = plt.subplot(111)
plt.subplots_adjust(left=0.25, bottom=0.1, right=0.75, top=0.9, wspace=0, hspace=0)

# plot a line. When clip_on is set to False, the line is extended beyond the axes
ax.plot(np.linspace(0,2),np.sin(np.linspace(0,2)),clip_on=False)
plt.xlim([0,1])
plt.ylim([0,1])

# plot a bitmap. Although clip_on is set to False, it is clipped by the axes
logo = plt.imread(get_sample_data("logo2.png", asfileobj=False))
left,right, bottom, top=0.25,0.25+1.12,0.25,0.25+0.24
ax.imshow(X=logo,extent=(left, right, bottom, top),clip_on=False)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/10431558/67646282-bf3a5500-f903-11e9-8713-1305721de741.png)

**Expected outcome**
The matplotlib logo shouldn't be clipped by the axes, since clip_on was set to False.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: : 3.1.1 (pip installation)
  * Matplotlib backend: Qt5Agg
  * Python version: 3.6

**Comment by anntzer** [comment]
This should be fixed in mpl3.2 (by https://github.com/matplotlib/matplotlib/pull/14774).

**Comment by ImportanceOfBeingErnest** [comment]
Reopening, because the code in the OP gives the same result in master, so either this is not fixed; or the use of `clip_on=False` isn't documented correctly.

**Comment by anntzer** [comment]
Woops, sorry about that.  It looks like
```patch
diff --git i/lib/matplotlib/image.py w/lib/matplotlib/image.py
index db3bf36cf..7de60d23d 100644
--- i/lib/matplotlib/image.py
+++ w/lib/matplotlib/image.py
@@ -876,7 +876,8 @@ class AxesImage(_ImageBase):
         transformed_bbox = TransformedBbox(bbox, trans)
         return self._make_image(
             self._A, bbox, transformed_bbox,
-            self.get_clip_box() or self.axes.bbox,
+            (self.get_clip_box() or self.axes.bbox) if self.get_clip_on()
+            else self.figure.bbox,
             magnification, unsampled=unsampled)
 
     def _check_unsampled_image(self, renderer):
```
fixes it?

**Comment by ImportanceOfBeingErnest** [comment]
Looks like it; I wonder if images would actually *need* a clip_box/path. Seems for any other artist it just works through the `draw` method's call to

https://github.com/matplotlib/matplotlib/blob/eb8327da73c0e85c47308752715777fb9efca494/lib/matplotlib/image.py#L613

which then sets the clipping

https://github.com/matplotlib/matplotlib/blob/eb8327da73c0e85c47308752715777fb9efca494/lib/matplotlib/artist.py#L858

**Comment by anntzer** [comment]
IIRC(?) most artists get their parent axes' clip box via Axes.add_lines/add_foo/..., it's just that images used to do things differently but it's a good time to rationalize that as well...
