### ISSUE TITLE
zorder is not respected by all parts of `errorbar` 

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#1622]
This was found by via a SO question  (http://stackoverflow.com/questions/14003572/how-to-force-errorbars-to-render-last-with-matplotlib)

It looks like the root cause of this issue is that LineCollections do not take zorder as a parameter.

The hacky work around is to put negative zorder on the lines you want to be below the error bars.

```
import matplotlib.pyplot as plt
fig = plt.figure()
ax = plt.gca()
[ax.plot(rand(50),color='0.75') for j in range(122)];
ax.errorbar(range(50),rand(50),yerr=.3*rand(50))
plt.draw()
```

![eb_wrong](https://f.cloud.github.com/assets/199813/28725/b36a15da-4c8a-11e2-805c-d1c911a9c71f.png)

```
fig = plt.figure()
ax = plt.gca()
[ax.plot(rand(50),color='0.75',zorder=-32) for j in range(122)];
ax.errorbar(range(50),rand(50),yerr=.3*rand(50))
plt.draw()
```

![eb_hack](https://f.cloud.github.com/assets/199813/28726/be8e765e-4c8a-11e2-8c22-89a6ebc28c3b.png)

**Comment by agbuckley** [comment]
I just encountered the same problem with mpl 1.4.2:

![rand](https://cloud.githubusercontent.com/assets/926164/10029346/3972c2f8-6169-11e5-9820-bdbf7c0a8738.png)

Has this problem resurfaced? I haven't seen any mention of it in the changelog up to 1.4.3.

**Comment by tacaswell** [comment]
@agbuckley This isn't a bug that we can easily fix.  If you give a z-order to the errorbar (which is greater than 2) it will now behave correctly.

The underlying issue here is that the errorbar is rendered as three artists, and the lines are rendered as 522 artists.  The vertical lines are drawn as a collection, everything else is a line.  The collection and lines are stored in different internal lists which are then concatenated and sorted (in a stable manner) by zorder which determines the draw order. The stable part is important because as the lists are appended too in the order they are added to the axes.  Hence, in this case the vertical lines (which are a collection) are drawn first, then the gray lines, then blue line and the caps.

I have thoughts on how to fix this, but they involve a rather major refactoring of the internals and are at least a year out.

**Comment by agbuckley** [comment]
Ah, I see: the bug that was fixed was non-passing of the z-order to rendering of errorbar verticals, but the counterintuitive implicit ordering (with no zorder argument) is still just part of how mpl is, for now? Good to know... and best of luck for finding time & enthusiasm for that internal refactoring! Thanks.

**Comment by fkbreitl** [comment]
This bug is back in matplotlib 2.0.0!

**Comment by dstansby** [comment]
The minimal example at the top of this bug still doesn't work, so I'll reopen to reflect that. In the meantime, passing `zorder=3` to `plt.errorbar` seems to do the trick.

**Comment by tacaswell** [comment]
![image](https://user-images.githubusercontent.com/199813/113462222-dc732d00-93ed-11eb-8985-379e96433da5.png)

```python
import matplotlib.pyplot as plt
import numpy as np
fig = plt.figure()
ax = plt.gca()
[ax.plot(np.random.rand(50),color='0.75') for j in range(122)];
ax.errorbar(range(50),np.random.rand(50),yerr=.3*np.random.rand(50), capsize=2)
plt.draw()
plt.show()
%history
```

fixed by #18216
