### ISSUE TITLE
Cannot configure matplotlib rcparams for plot color

### ISSUE THREAD

**Issue by PalashSharma15** [matplotlib/matplotlib#16434]
**According to official documentation below code snippet should return a plot with red lines**
[Documentation is here](https://matplotlib.org/tutorials/introductory/customizing.html#dynamic-rc-settings)

```import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
data = np.random.randn(50)
mpl.rcParams['lines.color'] = 'r'
plt.plot(data)
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/32895810/74007654-d5e15500-49a4-11ea-8dc4-85a703e892b3.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/32895810/74007665-dda0f980-49a4-11ea-80f3-5f110570a61e.png)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.3

**Comment by tacaswell** [comment]
Indeed, that does not work as expected.  

The line's styles are pulled from the property cycle so I suspect this has been broken for quite some time...

**Comment by anntzer** [comment]
I don't know if it's really a *bug* or a bad interaction between two rcParams that both want to do the same thing (i.e. set a line's color)...

**Comment by QuLogic** [comment]
I'm not sure if that example is working by fluke or not, because the next one says `color='g'`, but the line is clearly not green.

**Comment by ImportanceOfBeingErnest** [comment]
I would consider this as a pure documentation issue. When the property cycler got its own rcParam in mpl 1.5 this part of the tutorial hasn't been updated.  
The rc file has a comment in it saying 

    #lines.color       : C0      ## has no affect on plot(); see axes.prop_cycle

So for ***lines*** this works fine:

```
plt.rcParams["lines.color"] = "green"
plt.gca().add_line(plt.Line2D([0, 1], [0, 1]))
```

but `plt.plot()` will use the cycler instead.

<hr>

To do:

* Choose a different property of lines, e.g. `linestyle`, to show the effect of two different parameters being set via rc Params in the [dynamic-rc-settings](https://matplotlib.org/tutorials/introductory/customizing.html#dynamic-rc-settings) section of the tutorial.
* (optionally) Add another example showing how to dynamically change the property cycler, *or* link to the [Styling with cycler](https://matplotlib.org/tutorials/intermediate/color_cycle.html?highlight=prop_cycle#styling-with-cycler) tutorial for how to use the cycler to change the usual `plot` color.

**Comment by tacaswell** [comment]
I think it looks like it works by a fluke that the first color in the ggplot color cycle is red-orangish.

**Comment by maij** [comment]
I've just encountered this issue as well, there is a general issue with default line coloring not being consistent across different functions. I wish to add to this discussion further scenarios.
This is especially problematic for use of dark backgrounds, where many thing default to black (toggle `plt.style.use('dark_background')` below to see the significance of default colors.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
# plt.style.use('dark_background')

data = np.random.rand(100)
plt.figure()
with mpl.rc_context({'lines.color':'white}):
   plt.plot(data) # uses axes.prop_cycle, defaults to blue
   plt.hlines(0.5, 0, 100) # not sure what this uses, defaults to black
   plt.annotate('test', (0, 0), (100, 1), 
                        arrowprops=dict(arrowstyle='<->, head_width=1'))
                        # same as above, the arrows drawn default to black
```

Some, perhaps unexpected behaviour is that, to change the annotation line color, you need to change the patch edge color.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
# plt.style.use('dark_background')

plt.figure()
data = np.random.rand(100)
with mpl.rc_context({'patch.edgecolor':'white'}):
   plt.plot(data) # uses axes.prop_cycle, defaults to blue
   plt.hlines(0.5, 0, 100) # not sure what this uses, still defaults to black
   plt.annotate('test', (0, 0), (100, 1), 
                        arrowprops=dict(arrowstyle='<->, head_width=1')) 
                        # Now correctly draws a white arrow
```

**Comment by ImportanceOfBeingErnest** [comment]
Those are two additional new issues.

1. The default color for `hlines` is set in the signature `hlines(..., colors="k", ...)`. This could of course be changed to `hlines(..., colors=None, ...)`, falling back to the `lines.color` rc parameter.
2. The FancyArrowPatch of an annotation needs to be changed via `patch.<parameter>`. Not sure if that is really undesired - seems logical to me.

**Comment by maij** [comment]
I was thinking this could be a separate issue, thank you for clarifying these matters.
I don't really understand why `hlines`, for example, would not automatically default to the matplotlib rcParams. I'll raise this as a separate issue.
As for the `FancyArrowPatch`, I'm happy to concede that an arrow object is distinct from a line object.

**Comment by PalashSharma15** [comment]
> 
> 
> **According to official documentation below code snippet should return a plot with red lines**
> [Documentation is here](https://matplotlib.org/tutorials/introductory/customizing.html#dynamic-rc-settings)
> 
> ```
> import matplotlib as mpl
> import matplotlib.pyplot as plt
> data = np.random.randn(50)
> mpl.rcParams['lines.color'] = 'r'
> plt.plot(data)
> ```
> 
> **Actual outcome**
> 
> ![image](https://user-images.githubusercontent.com/32895810/74007654-d5e15500-49a4-11ea-8dc4-85a703e892b3.png)
> 
> **Expected outcome**
> 
> ![image](https://user-images.githubusercontent.com/32895810/74007665-dda0f980-49a4-11ea-80f3-5f110570a61e.png)
> 
> **Matplotlib version**
> 
>     * Operating system: Windows 10
> 
>     * Matplotlib version: 3.1.2
> 
>     * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
> 
>     * Python version: 3.7.3

My issue was resolved by [this answer](https://stackoverflow.com/a/60097044/8438777)

**Comment by ImportanceOfBeingErnest** [comment]
Reopening, because the issue is not resolved yet. The documentation is at the very least misguiding, so it needs to be updated - see https://github.com/matplotlib/matplotlib/issues/16434#issuecomment-583834800 for what needs to be done.

**Comment by ImportanceOfBeingErnest** [comment]
Fixed by #16564
