### ISSUE TITLE
ax.secondary_xaxis gives "divide by zero encountered in true_divide" when no zero is present on original axis

### ISSUE THREAD

**Issue by felixvennberg** [matplotlib/matplotlib#18924]
**Bug summary**

The ax.secondary_xaxis('top', functions = (forward,inverse)) function throws a "RuntimeWarning: divide by zero encountered in true_divide" for forward/inverse functions of the form 1/x even when no zero is present on the original axis. 

The problem is present in the example on the secondary axis matplotlib page: https://matplotlib.org/3.1.0/gallery/subplots_axes_and_figures/secondary_axis.html

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(constrained_layout=True)
x = np.arange(0.02, 1, 0.02)
np.random.seed(19680801)
y = np.random.randn(len(x)) ** 2
ax.loglog(x, y)
ax.set_xlabel('f [Hz]')
ax.set_ylabel('PSD')
ax.set_title('Random spectrum')


def forward(x):
    return 1 / x


def inverse(x):
    return 1 / x

secax = ax.secondary_xaxis('top', functions=(forward, inverse))
secax.set_xlabel('period [s]')
plt.show()

```
```
Console output: 
RuntimeWarning: divide by zero encountered in true_divide
 return 1 / x

```
Using: 
Windows 10
Matplotlib version 3.3.2
Backend: Qt5Agg
Python: 3.8.6
Numpy: 1.19.2

Python installed from source. 
All packages installed via pip.

Even though no zero is included in the original xaxis, it is indeed passed to the "forward" and "inverse" functions sometime during the function call to secondary_xaxis. 

A workaround is to simply ignore the error message with: 
```python
def forward(x)
    with np.errstate(divide='ignore'):
        return 1/x
```
I could not find any more documentation on the inner workings of the secondary axis function, is this the intended behavior?

**Comment by timhoffm** [comment]
Thanks for the report. This has just been fixed in #18905.

**Comment by Rainald62** [comment]
@timhoffm
This is not fixed. Please reopen.

Versions 
matplotlib 3.3.4
python 3.9.0

MWE
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

def invert(x):
    return 1 / x

ax.set_xlim(0.5, 1)
secax = ax.secondary_xaxis('top', functions=(invert, invert))
plt.show()
```
Console output:
```
Warning (from warnings module):
  File "C:/Projekte/2020_Precision-Stopping_Issue/Oszi/test secondary_xaxis.py", line 6
    return 1 / x
RuntimeWarning: divide by zero encountered in true_divide

```

**Comment by anntzer** [comment]
I can repro as of master.

**Comment by jklymak** [comment]
I think it's up to the user to protect against divide by zero here?  The problem is just our default axis limits are 0-1 so the function needs to handle that.  I doubt there is a robust way to handle it from matplotlib.

**Comment by jklymak** [comment]
So the user needs to do 
```
def invert(x):
    with np.errstate(divide='ignore'):
        return 1 / x
```
 I guess we could better document that?  What else can we do here?

**Comment by Rainald62** [comment]
Why using defaults after `set_xlim(0.5, 1)`?

**Comment by anntzer** [comment]
That numpy raises a "division" error for log(0) is something on numpy's side, so if you want you can try to argue with them, but that's not something we can do anything about.

OTOH I agree that given if the user explicitly set the limits to not include zero *even before creating the secondary axes*, it would be preferable if the secondary axes' machinery doesn't try to evaluate the conversion functions at zero in that case (or anywhere out of the requested range, for that matter).

**Comment by jklymak** [comment]
> OTOH I agree that given if the user explicitly set the limits to not include zero even before creating the secondary axes

Sure, but this isn't a problem with the limits per-se, its a problem with `FuncScale` trying to handle default ticks at 0.  I'd be all for trying to stop the ticker from putting a default tick at zero, but...
