### ISSUE TITLE
Unexpected tick spacing for datetime axes

### ISSUE THREAD

**Issue by tillahoffmann** [matplotlib/matplotlib#19090]
### Bug report

**Bug summary**

Tick labels on some `datetime` axes are not spaced regularly by default. Feel free to close if this behaviour is intended.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt

# Set up some datetime values
x = np.asarray(['2020-07-06', '2020-08-02', '2020-08-21', '2020-09-07',
                '2020-09-25', '2020-10-14', '2020-11-04', '2020-11-22'], 
               dtype=np.datetime64)
# Plot the dates
fig, ax = plt.subplots()
ax.scatter(x, np.arange(len(x)))
# Optional, make the labels a bit more readable
plt.setp(ax.xaxis.get_ticklabels(), rotation=30)
# Get the tick locations and calculate spacings
locs = ax.xaxis.get_ticklocs()
deltas = np.diff(locs)
deltas
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/966348/101691350-7d686180-3a66-11eb-9078-150e050cb760.png)

```
# result of `deltas` statement
array([21., 10., 21., 10., 21.,  9., 21., 10., 21.])
```

**Expected outcome**

The same plot but with regular spacing of ticks.

**Matplotlib version**

  * Operating system: macOS Big Sur 11.0.1
  * Matplotlib version: 3.2.2 (installed via `pip` in a virtual environment)
  * Matplotlib backend (`print(matplotlib.get_backend())`): `module://ipykernel.pylab.backend_inline`
  * Python version: 3.8.1 (default, Jun 21 2020, 11:47:47); [Clang 11.0.0 (clang-1100.0.33.17)]
  * Jupyter version (if applicable):
    * jupyter core     : 4.6.3
    * jupyter-notebook : 6.0.3
    * qtconsole        : 4.7.5
    * ipython          : 7.16.1
    * ipykernel        : 5.3.2
    * jupyter client   : 6.1.5
    * jupyter lab      : 2.2.9
    * nbconvert        : 5.6.1
    * ipywidgets       : 7.5.1
    * nbformat         : 5.0.7
    * traitlets        : 4.3.3
  * Other libraries: `numpy==1.19.0`

**Comment by jklymak** [comment]
There was a mis-config that was fixed a while ago,  I think for master you get the more-pleasing:

![Master](https://user-images.githubusercontent.com/1562854/101699603-46775900-3a30-11eb-8b72-c35fe528a542.png)

If you do not like this, then you can do:

```
import matplotlib.dates as mdates
loc = mdates.AutoDateLocator(interval_multiples=False)
ax.xaxis.set_major_locator(loc)
```

To get:

![intmultFalse](https://user-images.githubusercontent.com/1562854/101699633-555e0b80-3a30-11eb-86e5-046aceebd333.png)

You may also want to try ConciseDateFormatter:

![Concise](https://user-images.githubusercontent.com/1562854/101699785-aec63a80-3a30-11eb-9a58-e7217e0c046e.png)

**Comment by tillahoffmann** [comment]
That's great, thank you for the speedy reply, @jklymak. I'll install from master.

**Comment by jklymak** [comment]
Pretty sure its fixed in 3.3.3 as well if you'd like to stick to released versions.

**Comment by tillahoffmann** [comment]
Maybe I closed this prematurely: I still have the same issue with `3.3.3` and also with the nightly wheel at `PRE_URL=https://7933911d6844c6c53a7d-47bd50c35cd79bd838daf386af554a83.ssl.cf2.rackcdn.com/
pip install -f $PRE_URL --pre matplotlib`. Will try installing master from source.

**Comment by jklymak** [comment]
Oh yeah, bummer it was pushed off to 3.4.0 which isn't out yet.  Sorry.  https://github.com/matplotlib/matplotlib/pull/17727

**Comment by tillahoffmann** [comment]
Your suggestion of

```python
loc = mdates.AutoDateLocator(interval_multiples=False)
ax.xaxis.set_major_locator(loc)
```

helped me resolve the problem. Thank you. 👍
