### ISSUE TITLE
Cannot save a very large (pixels) figure

### ISSUE THREAD

**Issue by miguelpenc** [matplotlib/matplotlib#19462]
anaconda:
  - python version: 3.7.4
  - matplotlib version: 3.0.3

Trying to save a pixel-perfect image from an array of 32768x32768 I get a segmentation fault.

Step to reproduce:
```python
# imm is a 32768x32768 numpy array of int32.
n_inch = int(2**6)
fig = figure(frameon=False, figsize=(n_inch, n_inch)) 
ax = fig.add_axes([0, 0, 1, 1])
ax.imshow(imm, origin='lower', cmap='bone_r', interpolation='none')

fig.savefig('./very_large.tiff', dpi=imm.shape[0]//n_inch) # This line gives segmentation fault
```

**Comment by tacaswell** [comment]
Can you try with 3.3 ?  3.0 is pretty old and we have fixed a number of these "too big" bugs.   I can not reproduce this because I run out of memory and have my Python process killed while trying to render (but it looks like OOM not segfault).

There is also some work on the default branch (which will be release in 3.4) on large images https://github.com/matplotlib/matplotlib/pull/19210 which maybe relevent here.

From what you are doing in this example, it does not look like you are making use of any of Matplotlib's features other than color mapping to get a false-color image.  You may be better off doing the color mapping and directly writing out the tiff, something like:

```python
from matplotlib.colors import Normalize
from matplotlib.cm import get_cmap
import tifffile   # https://pypi.org/project/tifffile/

cmap = get_cmap('bone_r')
scaled_im = Normalize()(imm)
color_mapped_image = cmop(scaled_im)
tifffile.imwrite('very_large.tiff', data=color_mapped_image
```

**Comment by miguelpenc** [comment]
I can confirm is still an issue in 3.3.2 under python 3.8. Probably is the same bug than #19210
Thanks for pointing out the library tifffile, worked like a charm.
