### ISSUE TITLE
Error when typing diacritic characters in TextBox

### ISSUE THREAD

**Issue by johnbow** [matplotlib/matplotlib#19744]
### Bug report

**Bug summary**

Typing a [diacritic](https://en.wikipedia.org/wiki/Diacritic) character (e.g. ^, `, ´) in a TextBox widget raises a TypeError. This also occurs when you press CapsLock. This prevents the user from entering some characters like "^" or using CapsLock.

**Code for reproduction**

```python
from matplotlib import pyplot as plt
from matplotlib.widgets import TextBox

fig, ax = plt.subplots(figsize=(6, 3))
fig.subplots_adjust(bottom=0.2)
text_box_ax = fig.add_axes([0.4, 0.02, 0.5, 0.06])
text_box = TextBox(text_box_ax, "Type diacritic character (e.g. ^): ")
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "\matplotlib\cbook\__init__.py", line 196, in process
    func(*args, **kwargs)
  File "\matplotlib\widgets.py", line 790, in _keypress
    if len(key) == 1:
TypeError: object of type 'NoneType' has no len()
```

**Expected outcome**
Normal behaviour of those characters when typing them in editors or searchbars etc.

**Matplotlib version**

  * Operating system: windows 10, build 19041.867
  * Matplotlib version: `3.2.2`
  * Matplotlib backend: `TkAgg`
  * Python version: 3.8
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by tacaswell** [comment]
Can you try with one of the mpl3.4 release candidates?  We very recently merged an overhaul of how keys are handled.

**Comment by johnbow** [comment]
@tacaswell
> 
> 
> Can you try with one of the mpl3.4 release candidates? We very recently merged an overhaul of how keys are handled.

I just tried with mpl 3.4rc3 and it actually solves the issue partially! It does not raise errors anymore and allows the use of CapsLock correctly, but it still does not write diacritic characters to the TextBox, but ignores them.

**Comment by diegopetrola** [comment]
I just tested with matplotlib version `3.4.1` and got this:

![image](https://user-images.githubusercontent.com/3846018/113246919-57becc80-9290-11eb-81e5-aaec821e04f2.png)

So I believe the issue is solved.

**Comment by johnbow** [comment]
Also tried with version `3.4.1` and it still doesn't work. The problem is not the label but the user-input of the TextBox. Characters that a standard keyboard would not print directly but only after a second keypress are not being written at all. This prohibits users of entering such characters like "^" which could be interpreted by a program as a power symbol.

**Comment by diegopetrola** [comment]
Oh, I misunderstood the problem, sorry.

**Comment by QuLogic** [comment]
> Characters that a standard keyboard would not print directly but only after a second keypress are not being written at all.

Those are dead keys; I don't know how to fix Tk to see them, but that's where one should look.

**Comment by dstansby** [comment]
This seems to be a Tk specific issue; I've just tried and inputting ^ works fine on other backends.

**Comment by oscargus** [comment]
I just tried this on my CentOS 7 machine and found that the Tk backend is the **only** backend that supports diacritics...
