### ISSUE TITLE
[Bug]: using `set_offsets` on scatter object raises TypeError

### ISSUE THREAD

**Issue by gtimoshaz** [matplotlib/matplotlib#21803]
### Bug summary

`plt.scatter` can accept datetime as arguments, but `set_offsets` method of it's returns cannot.

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10)
y = np.sin(x)
d = x * np.timedelta64(24, 'h') + np.datetime64('2021-11-29')

sc = plt.scatter(d, y) # shows a plot
sc.set_offsets(list(zip(d, y))) # clears the plot so it becomes just white square
```

### Actual outcome

The scatters just disappear if you use other `timedelta64` units than `D`, also if you use other date unit, than day.

### Expected outcome

Excepted outcome is to update positions of scatters

### Operating system

Arch

### Matplotlib Version

3.5.0

### Matplotlib Backend

Qt5Agg, `'module://ipympl.backend_nbagg'`

### Python version

Python 3.9.6

### Jupyter version

3.1.7

### Installation

conda

**Comment by jklymak** [comment]
Thanks, but this has been fixed, at least as of 3.5, so I'll close.

**Comment by gtimoshaz** [comment]
Well, I've just updated to 3.5.0 and the bug is still here with the exact same error

**Comment by jklymak** [comment]
Please update the issue with the non working code and the error message. Thanks!

**Comment by jklymak** [comment]
Agreed - `set_offset` coerces to float, which of course gets rid of your datetime.  As a work around, you can convert to float before passing: `list(zip(mdates.date2num(d), y))` but this should also be fixed on our side.  Thanks!
