### ISSUE TITLE
[Bug]: Colorbar spacing property is not working

### ISSUE THREAD

**Issue by Engineer-C** [matplotlib/matplotlib#22432]
### Bug summary

Changing the _**spacing**_ property of colorbar does not work.

### Code for reproduction

```python
import matplotlib
from matplotlib.colors import TwoSlopeNorm
import matplotlib.pyplot as plt
from matplotlib import cm


norm = TwoSlopeNorm(vmin=-3, vcenter=0, vmax=30)

fig, ax = plt.subplots(nrows=1, ncols=2)
fig.suptitle(f'matplotlib {matplotlib.__version__}')
fig.colorbar(mappable=cm.ScalarMappable(norm=norm, cmap='coolwarm'), cax=ax[0], spacing='uniform')
fig.colorbar(mappable=cm.ScalarMappable(norm=norm, cmap='coolwarm'), cax=ax[1], spacing='proportional')
```

### Actual outcome

![3 5 1](https://user-images.githubusercontent.com/79517955/153164619-c36700b2-7cec-4fb1-9cd8-5f091de0a839.png)

### Expected outcome

![3 4 3](https://user-images.githubusercontent.com/79517955/153164648-b2a0c24f-6a5b-48c9-803d-ce814c128365.png)

### Additional information

Before the 3.5, the spacing keyword worked, but after updating to 3.5 'uniform' spacing property, which is default, does not work.

### Operating system

openSUSE Leap 15.3

### Matplotlib Version

3.5.1

### Matplotlib Backend

agg

### Python version

3.8.12

### Installation

conda

**Comment by jklymak** [comment]
Any chance you can test on master?  Pretty sure this was fixed and will be out in 3.5.2. Thanks and sorry for the bother.

**Comment by Engineer-C** [comment]
Installed from source and tested on both main and v3.5.x branches.
Seems the issue was not fixed.

4fe8472
![4fe8472](https://user-images.githubusercontent.com/79517955/153327187-b13e459f-8bca-4329-a9bc-114d71d15d98.png)

5b07441
![5b07441](https://user-images.githubusercontent.com/79517955/153327241-66b4b1a7-5bbf-4c17-babf-2727c467f7cd.png)

Thank you for your quick reply.

**Comment by jklymak** [comment]
Sorry I missed that this was a continuous norm.  Yes, the behaviour was explicitly changed.  If you want the old behaviour you can set the y scale to linear on the colorbar.  This was discussed in previous issues though I'm away from my computer so cannot easily look up which one.  Thanks.

**Comment by Engineer-C** [comment]
Thanks, solved the issue with v3.5.1 with setting yscale of axis to linear.

```
import matplotlib
from matplotlib.colors import TwoSlopeNorm
import matplotlib.pyplot as plt
from matplotlib import cm


norm = TwoSlopeNorm(vmin=-3, vcenter=0, vmax=30)

fig, ax = plt.subplots(nrows=1, ncols=2)
fig.suptitle(f'matplotlib {matplotlib.__version__}')
fig.colorbar(mappable=cm.ScalarMappable(norm=norm, cmap='coolwarm'), cax=ax[0])
ax[0].set(yscale='linear')
fig.colorbar(mappable=cm.ScalarMappable(norm=norm, cmap='coolwarm'), cax=ax[1])
```

![3 5 1_fixed](https://user-images.githubusercontent.com/79517955/153350688-0d00de54-9458-4612-8d0e-f69dcd25d3c3.png)

I think the reference needs to be updated with updated behaviour.
[matplotlib.pyplot.colorbar](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.colorbar.html#)

**Comment by Engineer-C** [comment]
#22197

**Comment by Engineer-C** [comment]
Found previous discussions.
#20993 and #22197

**Comment by jklymak** [comment]
The spacing argument is really only applicable to discrete norms (BoundaryNorm) which I thought the docs already said, but now I'm not sure.  

Certainly the new behaviour is consistent with the doc (uniform means each "color" gets the same space). What we don't have is a "proportional" setting for continuous colormaps except via setting the y scale to linear.  

Personally I'd just alter the doc string to be clearer that spacing really only applies to discrete colormaps.  I'm surprised that even worked before, and definitely was untested.  

Thanks for your understanding on this.
