### ISSUE TITLE
[Bug]: DPI keeps doubling when creating a new MatPlotLib QtWidget in qt6

### ISSUE THREAD

**Issue by hydroEng** [matplotlib/matplotlib#26380]
### Bug summary

I ran into this bizarre bug, I am not sure if it's a skill issue on my end, but I am trying to embed a plot in my qt6 application. Allowing the user to plot and replot for some reason keeps increasing the sizes of my chart elements, but *only* when I have display scaling on (e.g. 125%, 150% etc). To illustrate:

![wat](https://github.com/matplotlib/matplotlib/assets/59785388/286c07a7-e217-4fea-82db-817f7c3b3b10)

See below for the code, basically I am creating a new plot every time there is a mouse click on that row. Embedding `print(self.chart.figure.dpi)` shows that my plot's dpi keeps doubling every other time I trigger a click. Console output:

```
100.0
100.0
200.0
200.0
400.0
400.0
```

I can workaround this by explicitly setting the figure DPI, e.g. figure.dpi = 100 when creating it. But I assume that means I'm giving up display scaling
        

### Code for reproduction

```python
class GraphView(QWidget):
    def __init__(self):
        super().__init__()
        self.layout = QVBoxLayout()
        self.separator = None
        self.chart = MplCanvas()

        self.figures = None

        self.init_widget()

    def init_widget(self):
        self.init_separator()
        self.layout.addWidget(self.separator)
        self.layout.addWidget(self.chart)
        self.setLayout(self.layout)
    ...
    # Note this is the code that triggers when I click a row.
    def update_graph(self, figure):

        self.chart.deleteLater()
        self.chart = MplCanvas(fig=figure)
    
        self.layout.addWidget(self.chart)
        self.layout.update()
```

### Actual outcome

Figure DPI keeps dynamically doubling

### Expected outcome

DPI shouldn't double like that, it's madness :frow

### Operating system

Windows, Linux

### Matplotlib Version

3.6.3

### Matplotlib Backend

QtAgg

### Python version

3.11.4

### Installation

pip

**Comment by tacaswell** [comment]
Can you please try with a newer version of Matplotlib?  I believe we have fixed this bug already.

**Comment by hydroEng** [comment]
Thanks @tacaswell, the issue is still present in ver 7.4.2. 

![image](https://github.com/matplotlib/matplotlib/assets/59785388/3d0b190a-ec10-41a1-9fb5-a659f8cc6234)

 If i get time I will write up some simple reproducible code.

**Comment by tacaswell** [comment]
Are you setting the DPI internally to your code?

Are you updating one `Figure` or do you have more than one Figure that you show/hide?  Do you do that show/hide by having more than one Canvas and then doing Qt things or do you have one canvas that you attach to each figure in turn?

**Comment by hydroEng** [comment]
(1) No, I am not setting DPI internally.
(2) More than one figure, clicking the QTableWidget row effectively just requests a new figure. Every time a request is made a new `MplCanvas` object (inherits `FigureCanvasQTAgg`, see above) is being created and added to the Qt window as a widget.

**Comment by tacaswell** [comment]
If you are creating new `Figure` and `FigureCanvasQtAgg` each time, where is the scaled-up DPI being persisted?  The source of the scaling is that on high DPI screens we upscale the user set DPI by what ever the pixel ratio is.  IF you then read that DPI and set it back you can get these "always gets bigger" loops.

**Comment by hydroEng** [comment]
honestly, I don't know, since I don't set dpi settings anywhere in my code. I'll try write something reproducible for you.

**Comment by QuLogic** [comment]
> the issue is still present in ver 7.4.2.

There is no such version of Matplotlib?

**Comment by hydroEng** [comment]
> > the issue is still present in ver 7.4.2.
> 
> There is no such version of Matplotlib?

Sorry, I meant version 3.7.2 **

**Comment by hydroEng** [comment]
@tacaswell I can reproduce this bug with the following code (using v. 3.7.2). It seems like this occurs when plotting preexisting figures on a canvas (if creating a new figure each time "plot" is clicked, there are no issues). So I guess the dpi info is persisting in the figure object? 

Recording:

![bug](https://github.com/matplotlib/matplotlib/assets/59785388/153d0a13-ca3d-4a02-b274-9185c8a59233)

Code:

```python
import sys
import matplotlib
import random

matplotlib.use('Qt5Agg')
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
from PyQt6.QtWidgets import QWidget, QVBoxLayout, QApplication, QPushButton
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg


class App(QWidget):

    def __init__(self):
        super().__init__()
        self.layout = QVBoxLayout()
        self.chart = Canvas()

        self.btn = QPushButton("Plot")
        self.figs = self.make_figs()
        self.btn.clicked.connect(self.show_plots)

        self.layout.addWidget(self.btn)
        self.layout.addWidget(self.chart)
        self.setLayout(self.layout)

    def show_plots(self):
        i = random.choice([0, 1])
        figure = self.figs[i]
        self.chart.deleteLater()
        self.chart = Canvas(fig=figure)

        self.layout.addWidget(self.chart)
        self.layout.update()

    def make_figs(self):
        # test figures:
        fig1, ax1 = plt.subplots()
        fig2, ax2 = plt.subplots()

        data1 = [5, 10, 15, 20]
        data2 = [[20, 30, 18, 12], [3, 5, 7, 8]]

        ax1.boxplot(data1)
        ax2.scatter(data2[0], data2[1])

        return [fig1, fig2]


class Canvas(FigureCanvasQTAgg):
    def __init__(self, fig=Figure()):
        super(Canvas, self).__init__(fig)


if __name__ == "__main__":
    app = QApplication(sys.argv)

    ex = App()
    ex.show()
    sys.exit(app.exec())

```

**Comment by tom-a-horrocks** [comment]
I am also experiencing this bug,  Matplotlib 3.10.7 and PySide 6.10.0. It happens each time I attach a new canvas to an existing Figure.

**Comment by timhoffm** [comment]
Possibly fixed through https://github.com/matplotlib/matplotlib/pull/29855#issuecomment-3141316594.

**Comment by tacaswell** [comment]
Not fixed by #29855 but there is a simple fix, PR coming.
