### ISSUE TITLE
[Bug]: Broken functionality: Qt5/PySide2, using interactive mode, fig.canvas.draw() then fig.canvas.flush_events() leaves plot in non-interactive state.

### ISSUE THREAD

**Issue by chrisgmorton** [matplotlib/matplotlib#28959]
### Bug summary

Matplotlib 3.9.0, PySide2 with Qt5 5.15.2, Python 3.11.9, IPython 8.25.0 (or jupter qtconsole 5.5.2)

The attached code leaves the plot in a non-interative state.

The blank figure comes up correctly with the plt.figure() call.  The plot draws correctly at fig.canvas.flush_events(). the final state is not interactive.

### Code for reproduction

```Python
import matplotlib
matplotlib.use('Qt5Agg')

import matplotlib.pyplot as plt
import numpy as np

x=np.arange(10)
y=x*x

plt.ion()

fig=plt.figure()
ax=fig.add_subplot(111)
line,=ax.plot(x,y)

fig.canvas.draw()
fig.canvas.flush_events()
```

### Actual outcome

Plot is not responsive but is displayed correctly.

### Expected outcome

Should be able to interact with the plot, including selection of toolbar buttons, zooming etc.

### Additional information

The submission is a simplified use-case of a more complex applicaion under development. The plots in the application used to be left in an interactive state once the applications simulation completes execution.

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.9.0

### Matplotlib Backend

Qt5Agg

### Python version

3.11.9

### Jupyter version

IPython 8.25.0 or jupyter qtconsole 5.5.2

### Installation

from source (.tar.gz)

**Comment by tacaswell** [comment]
If you run `%matplotlib qt` does it work?  If you do `plt.show(block=True)` or `plt.pause(5)` does it revive the figure?

My guess is that the input hook did not get setup so nothing is showing because the input hook is not being setup right, see https://matplotlib.org/3.6.3/users/explain/interactive_guide.html for details.

**Comment by chrisgmorton** [comment]
Yes, running %matplotlib qt prior to this script does resolve the issue for this test case. Also running commands show and pause after running the script does revive the plot. I'm just not sure how to achieve these same results in my application. I'm unclear what magic happens when executing %matplotlib qt but I can't put this in python code.

**Comment by chrisgmorton** [comment]
A workaround for this issue is to execute the python code from within my application (in jupyter qtconsole):
```
import IPython.core.getipython as ipy
ipython = ipy.get_ipython()
ipython.magic('%matplotlib qt')
```
This obviously just runs the associated ipython magic command. 
I have not dug in to look at what python code is run with this magic command but it may point to something that was changed on the matplotlib side to cause the regression.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/blob/0439b3779918962f331cf3efc078ce0008dbde20/lib/matplotlib/pyplot.py#L277-L318

try `pyplot.install_repl_displayhook()`.  We should be calling this on switching the backend so I suspect something is missed there.

Can you try using `qtagg` instead of `qt5agg` (if you want pyside2, import it first and we will detect it is imported and use it).  We have moved to a single backend for all versions/bindings of Qt that supports both 5 and 6 (and I expect to fold 7 in when ever that happens). My guess is that the qt5agg string is not getting correctly mapped to a GUI framework so the input hook is not being installed.

**Comment by chrisgmorton** [comment]
```plt.install_repl_displayhook()``` did not resolve the issue. This was executed after ```matplotlib.use('Qt5Agg')``` and import ```matplotlib.pyplot as plt```.

I also separately tried ```QtAgg``` instead of ```Qt5Agg``` but this did not resolve the issue either.

**Comment by tacaswell** [comment]
@ianthomas23 This may be another bit of fallout from the eventhook shuffle.

**Comment by ianthomas23** [comment]
I can reproduced the problem and it turns out this is a manifestation of issue #28324 which was fixed in PR #28332. So all that is required it to upgrade Matplotlib to `> 3.9.0`.

**Comment by tacaswell** [comment]
I'm going to close this as resolved, @chrisgmorton please ping if upgrading to >3.9.0 does not fix it for you.
