### ISSUE TITLE
[Bug]: KeyError when hovering over interactive plot in ipython

### ISSUE THREAD

**Issue by lpilz** [matplotlib/matplotlib#29654]
### Bug summary

When hovering over an interactive plot, multiple `KeyError: 'buttons'` messages fire.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
%matplotlib widget

plt.plot([1, 2, 3, 4])
```

### Actual outcome

KeyError: 'buttons'

![Image](https://github.com/user-attachments/assets/236026ef-db61-42ce-ac95-1fafbdf2587f)

### Expected outcome

Hovering works without error

### Matplotlib Version

3.10.0

### Installation

None

**Comment by ianthomas23** [comment]
This is a duplicate of #29337 and matplotlib/ipympl#575, it is already fixed in PR matplotlib/ipympl#577 and released in ipympl 0.9.6. Please update your version of `ipympl`.

**Comment by lpilz** [comment]
@ianthomas23 This is wrong, it's a typo bug which is in the matplotlib backend_webagg_core.py . I fixed it in PR #29655  - just couldn't open it yet in good faith because the tests were still running.

**Comment by lpilz** [comment]
For some reason, we were encountering this bug even with ipympl 0.9.6 installed in the environment we were using. After restarting the kernel multiple times, we don't encounter the bug anymore - maybe a caching issue? Thanks!

**Comment by T-Wainwright** [comment]
Still getting the same error with matplitlib 3.10.3 and ipympl 0.9.7 on completely clean and uncached builds, don't think this can be should be closed yet.

**Comment by dprotter** [comment]
I am having the same issue with 3.10.3 / 0.9.7 on Ubuntu 24.04 in a fresh conda env. Had to roll back to 3.7.5 and 0.9.3 to get interactivity to work.

**Comment by ianthomas23** [comment]
This has been identified as a problem in VSCode.

**Comment by dprotter** [comment]
a problem with the jupyter extension? if you have it handy, could you link to the bug report?

**Comment by ianthomas23** [comment]
There is a discussion in #30337 with steps to reproduce the problem in VSCode whereas the problem does not occur in JupyterLab.
