### ISSUE TITLE
[Bug]: memory baking figure is not freed when figure is closed

### ISSUE THREAD

**Issue by dnicolodi** [matplotlib/matplotlib#29743]
### Bug summary

It seems that a reference to the figure object is kept in some global state. Executing the code below and closing the figures that pop up results in a linear increase in used memory. This happens with Matplotlib 3.9.1 and later. The latest release that does not exhibit the problem is Matplotlib 3.8.4.

### Code for reproduction

```Python
import gc
import psutil
import numpy as np
import matplotlib.pyplot as plt

p = psutil.Process()

d = np.linspace(0, 1, 1_000_000)

for i in range(10):
    fig, ax = plt.subplots()
    ax.plot(d)
    plt.show()
    gc.collect()
    print(p.memory_info().rss)
```

### Actual outcome

185729024
254550016
321282048
389459968
456253440
524554240
592330752
659394560
727457792
794468352

### Expected outcome

183324672
251961344
253427712
253464576
253493248
254521344
254529536
253464576
253468672
254476288

### Additional information

The leak has been introduced sometime between version 3.8.4 (which gives the expected outcome output above) and version 3.9.1 (which gives the actual outcome output above). It reproduces with Matplotlib version 3.9.4 and 3.10.1

### Operating system

Windows

### Matplotlib Version

3.9.1

### Matplotlib Backend

qtagg

### Python version

3.12.9

### Installation

conda

**Comment by timhoffm** [comment]
The pyplot figure manager still holds a reference to the figure. Use `plt.close(fig)` to remove that reference.

**Comment by dnicolodi** [comment]
Adding `plt.close()` does not make any difference.

**Comment by dnicolodi** [comment]
This is funny: this code
```python
import gc
import psutil
import numpy as np
import matplotlib.pyplot as plt

p = psutil.Process()

d = np.linspace(0, 1, 1_000_000)

for i in range(20):
    fig, ax = plt.subplots()
    sys.getrefcount(fig)
    ax.plot(d)
    plt.show(block=False)
    plt.close(fig)
    gc.collect()
    print(p.memory_info().rss)
```
reproduces the issue also on Matplotlib 3.8.4. It seems that running the GUI mainloop makes a difference.

**Comment by timhoffm** [comment]
With the qtagg backend I get on `main`

![Image](https://github.com/user-attachments/assets/777a1036-e15b-491d-9de9-23707566687b)

**Comment by dnicolodi** [comment]
Which reproducer did you ran to get that? Which version of Qt? Which Python binding? Can you please try to reproduce with a released version so we can determine if the issue is specific to my system? Unfortunately I don't have have a setup that easily allows me to compile Matplotlib from source.

**Comment by timhoffm** [comment]
Ok, the above was on my linux dev machine. I can reproduce a linear increase both on linux and windows in a fresh conda environment (`conda create -n mplleak -c conda-forge matplotlib python=3.12 psutil`). I also see this on both qtagg and tkagg backends, so it's likely not a backend-specific issue.

Needs further investigation, but we have a starting point now.

**Comment by tacaswell** [comment]
You have to run the GUI event loop to allow the c++ objects to be cleaned up.

**Comment by timhoffm** [comment]
> You have to run the GUI event loop to allow the c++ objects to be cleaned up.

I've tried using `Application.instance().processEvents()` (with qtagg backend), but the memory increases.


```
import gc
import psutil
import numpy as np
import matplotlib.pyplot as plt
from PySide6.QtWidgets import QApplication

p = psutil.Process()

d = np.linspace(0, 1, 1_000_000)

rss = []

for i in range(20):
    fig, ax = plt.subplots()
    plt.show(block=False)
    plt.close(fig)
    Application.instance().processEvents()
    gc.collect()
    rss.append(p.memory_info().rss)

plt.figure()
plt.plot(rss, 'o-')
plt.show()
```

**Comment by tacaswell** [comment]
I'm also seeing run-away memory usage, I think we need to bisect this back to sort out when this started to happen.

**Comment by tacaswell** [comment]
I wonder if this is also fixed by #28831  ?

**Comment by CalebBroman** [comment]
Verified that this is still a problem in version 3.11.0

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/259bcaa2-51c4-4a57-aa14-31485bf25fcc" />

```python
import matplotlib as mpl
import gc
import psutil
import numpy as np
import matplotlib.pyplot as plt
from PySide6.QtWidgets import QApplication

plt.switch_backend("qtagg")

p = psutil.Process()

rss = []

for i in range(200):
    fig, ax = plt.subplots()
    plt.show(block=False)
    plt.close(fig)
    QApplication.instance().processEvents()
    gc.collect()
    rss.append(p.memory_info().rss)


fig, ax = plt.subplots()
ax.plot(np.array(rss) / 1e6, 'o-')
ax.set_xlabel("Iterate")
ax.set_ylabel("Memory (MB)")
ax.set_title(f"matplotlib version {mpl.__version__}")
plt.show()


```
