### ISSUE TITLE
simple plotting of numpy 2d-arrays

### ISSUE THREAD

**Issue by thypad** [matplotlib/matplotlib#3420]
I want to plot a numpy 2d-array (i.e. an image), in the simplest way possible, with NO axes, whitespace, or any such thing. This should be the SIMPLEST use-case, and yet....It seems to be really hard. The PIL show() method for Image, does just that, but the documentation says it's inneficient and actually saves the image in a temporary file and then calls unix 'xv' utility (besides, the documentation states show() was made for debugging purposes).

Why is there no simple way in matplotlib to plot a matrix of values (i.e. image), with no bells and whistles?

The ideal would be something like:
          plt.imshow(2darray, barebones=True)

**Comment by alimehdi92** [comment]
I have implemented a fix for this issue.
I will add test-cases once the solution is accepted/agreed upon.

**Comment by WeatherGod** [comment]
I still fail to see what was insufficient with plt.figimage(). Is it that
you want a resampled image? Are you looking to have the image take up only
the subplot region?

**Comment by alimehdi92** [comment]
I am not able to plot a 2d array using figimage.

**Comment by tacaswell** [comment]
By default `figimage` tries to do a 1:1 pixel mapping so there is a 5x5 grid in there.  

```python
data = np.random.random((500,500))
plt.figimage(data)
plt.show()
```

Behaves as expected.

**Comment by alimehdi92** [comment]
should we still pursue this feature request? 
because it seems like the workaround would be to use plt.figimage() instead.
Thanks!

**Comment by tacaswell** [comment]
A convenience method that re-sizes the figure to match your image size (as `image.imsave` does) would probably be a good idea.  Maybe as a `resize` flag on `figimage`?  I have never actually had this use case (I always want axes) so not clear how useful this would be.

@WeatherGod , Thoughts?

**Comment by WeatherGod** [comment]
Actually, I was thinking of something along those lines, but you do need to
be careful due to the definition of figimage() to be not resampled. Perhaps
a new function like figshow() (which I worry is too similar to fig.show())?

The problem is that simply displaying 2d images can also easily be done by
other tools such as eog, imagemagick, Pillow, that I wonder what is the
point for us to do this as well? What is our value-add?

**Comment by alimehdi92** [comment]
I think this would be a nice-to-have feature. 
So, technically we can save a 2D-Array using the imsave? Just need to be able to show it?
Can we add a parameter in imshow(like resize/barebones), and remove the axes automatically and resize it?
Or are we still deciding if this feature is useful? :)
Thanks!!

**Comment by WeatherGod** [comment]
Yes, you can save an image using imsave(). I am against modifying imshow()
because it is an axes plotting method.

If anything, it would need to be a modification to figimage(), but I am
still not totally convinced given the plethora of image display tools
available elsewhere.

Ben Root

**Comment by ivanov** [comment]
#4315 was merged a while back implementing this functionality, so this issue can be closed.
