### ISSUE TITLE
Polar plot error bars don't rotate with angle

### ISSUE THREAD

**Issue by drwebb** [matplotlib/matplotlib#441]
In this example the errorbars do not align with the theta of bar. I posted this as a question at [stackoverflow](http://stackoverflow.com/questions/7224155/polar-plot-error-bars-dont-rotate-with-angle-in-matplotlib), and maybe the answer could be useful. Surely, this should not be default behavior though.

Example non-working code:

```
from numpy import *
from matplotlib import pyplot as py


r=zeros([16])
err=zeros([16]) 
for i in range(16):
    r[i]=random.randint(400,600)
    err[i]=random.randint(20,50)
theta=arange(0,2*pi,2*pi/16)
width = pi*2/16

fig = py.figure(figsize=(8,8))
ax = fig.add_axes([0.1, 0.1, 0.75, 0.79], polar=True)

bars = ax.bar(theta+pi/16, r, width=width, bottom=0.0,yerr=err)
ax.set_ylim(0,700)
py.show()
```

**Comment by isomerase** [comment]
It seems to me like this has been resolved? Attached is the plot that the figure produces.

![figure_1](https://cloud.githubusercontent.com/assets/5415776/8609065/fe479404-2655-11e5-9551-926c91521a04.png)

**Comment by QuLogic** [comment]
@isomerase I think it's only correct for you because you are using a style that hides the caps. The caps are still not rotated on master.

**Comment by tacaswell** [comment]
Still a bug :disappointed: but less visible now that the default style has no caps.

**Comment by thmosqueiro** [comment]
Just trying to understand the state of this issue: is this still open and scheduled for a future release? Could I submit a PR with a fix? 
After playing for a bit with a fork of this repository using a fix I've been using for a year now, I'm pretty sure I can patch it and submit a PR.  I just wanted to ask before spending too much time on it.

**Comment by dstansby** [comment]
I'm pretty sure this is still open, so if you have a fix a PR would be very appreciated!

**Comment by thmosqueiro** [comment]
Thanks for the reply, @dstansby. I just did some tests including my patch on the source code (version 2.1.2), and it seems to fix this problem in my plots, and the OP's plot without changing their script. An example using polar coordinates would be good too, what do you think? 

Also, I may have some minor questions, is gitter an appropriate channel for that?

**Comment by jklymak** [comment]
yes, gitter is great for dev chat, including minor dev questions.

**Comment by efiring** [comment]
Progress, @thmosqueiro?  It is OK to submit a PR that is "Work in Progress", if that can help move it along.

**Comment by thmosqueiro** [comment]
Hi @efiring. Apologies for the delay, I had to relocate recently. 

I actually have a local code that works and fixes the issues I had, and the issue originally reported. I like this idea of a "Work in Progress" kind of PR. I will post more info within a couple of days.

**Comment by RoryIAngus** [comment]
Hi @thmosqueiro, I was wondering if you had managed to find some time to do this?
I have just come across this issue and it would be helpful to get it resolved.

If you haven't got the time to invest, could you share your code and I can go through the process of getting updated?

Many thanks

**Comment by efiring** [comment]
@thmosqueiro If you and @RoryIAngus could come up with a PR that solves this problem cleanly, that would be much appreciated.  I would love to be able to close this issue, which dates back to 2011.

**Comment by thmosqueiro** [comment]
@efiring my current employment is prohibitive regarding open source contributions. I however would not mind sharing what I have done _until before I got hired_, which is documented and could be finalized by someone else. I talked to @jaquejbrito and she's interested in taking over my code and take responsibility over this task. I can most definitely provide her with feedback IRL and in here. Also, I'm sure if @RoryIAngus wants to also contribute, she'd be glad to have someone else to work with. 

So @efiring she says that she could get started as soon as tomorrow. Sounds good?

**Comment by efiring** [comment]
Thank you.

**Comment by RoryIAngus** [comment]
I would love to be of assistance.

Rory

Regards,



Rory Angus
Data Developer

M +61 421 769 765
E Rory.Angus@outlook.com

________________________________

**Comment by jaquejbrito** [comment]
Hi. 
I'll start checking the code. After we can start working on it. 
Tks

**Comment by RoryIAngus** [comment]
Some code to recreate the error showing the end cap issue and how it is not rotating but staying aligned to the horizontal plane.
```
from numpy import *
from matplotlib import pyplot as py

r = zeros([16])
err = zeros([16])
for i in range(16):
    r[i] = random.randint(400, 600)
    err[i] = random.randint(20, 50)
theta = arange(0, 2 * pi, 2 * pi / 16)
width = pi * 2 / 16

fig = py.figure(figsize=(8, 8))
ax = fig.add_axes([0.1, 0.1, 0.75, 0.79], polar=True)

bars = ax.bar(
    theta + pi / 16,
    r,
    width=width,
    bottom=0.0,
    yerr=err,
    capsize=15 # Capsize set to exaggerate issue
    )  
ax.set_ylim(0, 700)
py.show()
```

![image](https://user-images.githubusercontent.com/19604037/58296673-f74ee080-7e17-11e9-9984-dba419ce82ae.png)

**Comment by jaquejbrito** [comment]
Thanks for the sample code. I’m taking a look at thiago’s code, and should be able to stage his current changes in a forked repository soon.

**Comment by GentilsTo** [comment]
Hey, @jaquejbrito, any progress related?
