### ISSUE TITLE
Error while trying trendvis examples: ValueError: Expected 2-dimensional array, got 1

### ISSUE THREAD

**Issue by jorgesca** [matplotlib/matplotlib#4812]
Hi, I read about trendvis today and wanted to give it a try. I usually follow the master branch, which I update now and then. I updated mpl today, making sure I had a clean install (uninstalled mpl, did `git clean -fxd` as suggested in #3898, then run `python setup.py develop --user`) When I try some of the examples in [trendvis](https://github.com/matplotlib/trendvis) I get the error: `ValueError: Expected 2-dimensional array, got 1`.
As of today, trendvis includes 3 examples in the [README.rst](https://github.com/matplotlib/trendvis/blob/363e944482daa462d445d3b4bfaa7345fca13b2e/README.rst). The first one runs fine, while the second and the third give the aforementioned error. Matplotlib from Arch repos (1.4.3) works fine with these examples. The complete traceback for the 3rd example, labeled "Three-column XGrid with advanced features", follows:

``` python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-cc8e40190aa7> in <module>()
     55 
     56 # Draw a vertical bar behind the data - horizontal bars available too
---> 57 ex2.draw_bar(ex2.axes[1][2], ex2.axes[0][2], (45, 47), color='lightblue')
     58 
     59 # Ok to set axis limits after drawing on figure using TrendVis methods,

/home/jscandal/sw/trendvis/trendvis/trendvis/gridclass.py in draw_bar(self, ll_axis, ur_axis, bar_limits, orientation, zorder, **kwargs)
    720 
    721         ll_corner  = self._convert_coords(ll_axis, (lldx, lldy))
--> 722         ur_corner = self._convert_coords(ur_axis, (urdx, urdy))
    723 
    724         width, height = self._rect_dim(ur_corner, ll_corner)

/home/jscandal/sw/trendvis/trendvis/trendvis/gridclass.py in _convert_coords(self, axis, coordinates)
    919 
    920         # Convert to axes coordinates
--> 921         ax_coords = axis.transData.transform(coordinates)
    922 
    923         # Convert to figure coordinates

/home/jscandal/sw/matplotlib/matplotlib.py3/lib/matplotlib/transforms.py in transform(self, values)
   1301         # Ensure that values is a 2d array (but remember whether
   1302         # we started with a 1d or 2d array).
-> 1303         values = np.asanyarray(values)
   1304         ndim = values.ndim
   1305         values = values.reshape((-1, self.input_dims))

/usr/lib/python3.4/site-packages/numpy/core/numeric.py in asanyarray(a, dtype, order)
    512 
    513     """
--> 514     return array(a, dtype, copy=False, order=order, subok=True)
    515 
    516 def ascontiguousarray(a, dtype=None):

ValueError: Expected 2-dimensional array, got 1
```

**Comment by tacaswell** [comment]
go into where every `--user` installs to and forcibly remove anything that looks like it is from mpl/mpl-toolkits.

I also _strongly_ suggest not using `--user` and instead using `venv` or `conda` to create isolated dev environments.   That way when crazy things like this happen you just `rm -rf dev_venv` and start again.  Using `--user` you have messed system python.

The fact that it is coming out of `np.asanyarray` makes me think that you have not found the right files to delete :wink: .

**Comment by jorgesca** [comment]
I will re-check everything, or even get into using virtual environments, something I am not familiar with. I am still a bit confused as to what the cause of the issue could be. If I understood correctly, it could be due to conflicting/out of sync mpl and mpl-toolkits installs, and if I really understood well enough, we talk about compiled code. I had in this machine python2 and pyhton3 distro versions of mpl installed, and then a python2 and python3 development version that use the --user install method. I have manually verified that everything related to matplotlib was removed from ~/.local/xxx; I had also removed the system versions of mpl; then I cleaned the mpl git tree with the command you suggested; and after building mpl again the issue remained. Could it be because I use arch's versions of mpl dependencies (i.e. numpy, etc.)? Being a developer you certainly have a whole lot more experience than me with these issues, so I'll try to follow your advice and setup a virtual environment.

**Comment by tacaswell** [comment]
I don't _really_ understand what is going wrong here.  All I know is that I fought with this for quite a while and what solved it was deleting everything and trying again :stuck_out_tongue_winking_eye: 

Do you have a non-empty `PYTHONPATH`? 

One debugging tactic I have used to track this sort of things down is try to import things I am sure I have removed.  If I had started there more often I would have a few days of my life back.  

Make sure you got both `matplotlib` and `mpl_toolkits`.

**Comment by WeatherGod** [comment]
Also remember that an old Basemap install can mess things up, too.

**Comment by jorgesca** [comment]
I am closing this issue as I can't reproduce it anymore. This morning, after debugging code for several days (and still being lost), I `rm -rf mpl_git_dir` and `git clone https://github.com/matplotlib/matplotlib.git` again. Then I run `python setup.py develop` and the problem vanished. I cleaned the old git repo (`git clean -fxd`) and built matplotlib several times while debugging, all inside a conda environment, but somehow the issue was only solved when I re-cloned the repo from github. Thanks to those who helped and suggested things to try.

**Comment by jorgesca** [comment]
Sorry for the noise, but the reason I couldn't reproduce the bug anymore was that I had modified a file in trendvis:
```
diff --git a/trendvis/gridclass.py b/trendvis/gridclass.py
index d67b610..7c4d736 100644
--- a/trendvis/gridclass.py
+++ b/trendvis/gridclass.py
@@ -921,7 +921,7 @@ class Grid(object):
         ax_coords = axis.transData.transform(coordinates)
 
         # Convert to figure coordinates
-        fig_coords = self.fig.transFigure.inverted().transform(ax_coords)
+        fig_coords = self.fig.transFigure.inverted().transform(ax_coords.tolist())
 
         return fig_coords
```
Now, I don't understand what's going on really. I found that while debugging the code. Don't take it as a solution, more because the this bug seems to affect only me, but  those who understand the inner workings of matplotlib might get a clue. 
At this point I have done all I can imagine to eliminate a local installation problem: 
1- Removed mpl git repo, cloned it again
2- Set up a conda environment, installing all dependencies from anaconda, except trendvis and matplotlib
3- Created a new ipython profile, tried directly running the script with python

I am posting the three examples I used in the next comment (github doesn't let me attach these files). One of them works ok (single_column_xgrid.py) and the other two give the error described.

**Comment by jorgesca** [comment]
single_column_xgrid.py:
```python
import numpy as np
import matplotlib.pyplot as plt
import trendvis

# Pseudorandom data and plot attributes
random_generator = np.random.RandomState(seed=123)
yvals = random_generator.rand(10)

# Plot attributes
nums = 10
lw = 1.5

# convenience function trendvis.gridwrapper() is available
# to initialize XGrid and do most of the formatting shown here
ex0 = trendvis.XGrid([1,2,1], figsize=(5,5))

# Convenience function for plotting line data
# Automatically colors y axis spines to
# match line colors (auto_spinecolor=True)
trendvis.plot_data(ex0,
    [[(np.linspace(0, 9.5, num=nums), yvals, 'blue')],
     [(np.linspace(1, 9, num=nums), yvals*5, 'red')],
     [(np.linspace(0.5, 10, num=nums), yvals*10, 'green')]],
    lw=lw, markeredgecolor='none', marker='s')

# Get rid of extra spines
ex0.cleanup_grid()
ex0.set_spinewidth(lw)

ex0.set_all_ticknums([(2, 1)], [(0.2, 0.1), (1, 0.5), (2, 1)])
ex0.set_ticks(major_dim=(7, 3), minor_dim=(4, 2))

ex0.set_ylabels(['stack axis 0', 'stack axis 1', 'stack axis 2'])

# In XGrid.fig.axes, axes live in a 1 level list
# In XGrid.axes, axes live in a nested list of [row][column]
ex0.axes[2][0].set_xlabel('Main Axis', fontsize=14)

# Compact the plot
ex0.fig.subplots_adjust(hspace=-0.3)

plt.show()
```

two_row_ygrid_with_frame.py:
```python
import numpy as np
import matplotlib.pyplot as plt
import trendvis

# Pseudorandom data
random_generator = np.random.RandomState(seed=1234)
xvals = random_generator.rand(20)

# Plot attributes
numpts = 20
lw = 1.5

# Initialize a YGrid
ex1 = trendvis.YGrid([1, 2, 1], yratios=[1, 2], figsize=(5,5))

# Convenience function
trendvis.plot_data(ex1,
    [[(xvals, np.linspace(2, 18.5, num=numpts), 'blue')],
     [(xvals*5, np.linspace(1, 17, num=numpts),  'red')],
     [(xvals*10, np.linspace(0.5, 20, num=numpts), 'green')]],
    lw=lw, auto_spinecolor=True, markeredgecolor='none', marker='s')

# Remove extra spines, color stack (y) ticks
ex1.cleanup_grid()
ex1.set_spinewidth(lw)

# Tick, tick label formatting
ex1.set_all_ticknums([(0.2, 0.1), (1, 0.5), (2, 1)], [(2, 1), (2, 1)])
ex1.set_ticks(major_dim=(7, 3), minor_dim=(4, 2))
ex1.set_ylim([(0, 15, 20), (1, 0, 11)])

# Axes labels
ex1.set_xlabels(['stack axis 0', 'stack axis 1', 'stack axis 2'])
ex1.axes[0][0].set_ylabel('Main Axis 0', fontsize=14)
ex1.axes[2][1].set_ylabel('Main Axis 1', fontsize=14,
              rotation=270, labelpad=14)

# Draw boxes around each row
ex1.draw_frame()

# Broken axis cutout marks also available, try this instead of the frame:
# ex0.draw_cutout(di=0.05)

# Compact the plot
ex1.fig.subplots_adjust(wspace=-0.3)
plt.show()
```

three_column_ygrid_advanced.py:
```python
import numpy as np
import matplotlib.pyplot as plt
import trendvis

# Make some pseudorandom data
random_generator = np.random.RandomState(seed=123)
yvals = random_generator.rand(40)
yvals1 = np.copy(yvals)
yvals1[20:] = np.array([0.2, 0.3, 0.2, 0.5, 0.34, 0.24,
            0.15, 0.23, 0.26, 0.21] * 2)
numpts = 40
lw = 1.5
x0 = np.linspace(2, 49.5, num=numpts)
x1 = np.linspace(1, 49, num=numpts)
x11 = np.linspace(1.5, 47.5, num=numpts)
twin0 = np.linspace(2, 50, num=numpts)
twin1 = np.linspace(0.5, 48, num=numpts)

# Initialize XGrid and twin axes
ex2 = trendvis.XGrid([3, 4], xratios=[1, 3, 2], figsize=(5, 5),
                     startside='right')
ex2.make_twins([0, 1])

# Convenience function
trendvis.plot_data(ex2,
    [[(x0, yvals, 'blue')],
     [(x1, yvals1*5, 'red'), (x11, yvals1*5.2, 'orchid')],
     [],
     [(twin1, yvals*2, '0.5')]],
    lw=lw, marker=None)

# Adjust twinned y-axis positions for readability
ex2.move_spines(twin_shift=0.6)

# For any other kind of plot (fill_between, scatter, errorbar, etc),
# get axis and plot directly
# Note: ex2.axes[2][2] == ex2.get_axis(0, xpos=2, is_twin=True)
for ax in ex2.axes[2]:
    ax.fill_between(twin0, yvals+0.075, yvals-0.1,
                    edgecolor='none', color='darkorange')

# Handle axis ticks
ex2.cleanup_grid()
ex2.set_spinewidth(lw)
ex2.autocolor_spines()
ex2.set_all_ticknums([(2, 1), (2, 1), (2, 1)],
                     [(0.2, 0.1), (1, 0.5), (1, 0.25), (0.5, 0.25)])
ex2.set_ticks(major_dim=(6, 1.5), minor_dim=(3, 1))

ex2.set_ylabels(['row 0', 'row 1', 'twin row 0', 'twin row 1'])

# Rotate x-axis tick labels
for ax in ex2.fig.axes:
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=45)

# Draw a vertical bar behind the data - horizontal bars available too
ex2.draw_bar(ex2.axes[1][2], ex2.axes[0][2], (45, 47), color='lightblue')

# Ok to set axis limits after drawing on figure using TrendVis methods,
# TrendVis will reset the bar to the right place!
ex2.set_xlim([(0, 0, 3), (1, 13, 24), (2, 43, 50)])
ex2.set_ylim([(2, 0, 2)])

# matplotlib annotations supported
ex2.get_axis(0).text(0, 0.75, 'Text')

# Cutouts instead of frames
ex2.draw_cutout(lw=lw)

# Set the suptitle and compact the plot
ex2.fig.suptitle('Title', fontsize=16, y=1.05);
ex2.fig.subplots_adjust(hspace=-0.1)
plt.show()
```

**Comment by stefanv** [comment]
This issue seems to have been fixed in the latest version.

**Comment by jorgesca** [comment]
Hi @stefanv , did you actually run the examples with the development version of matplotlib (Please note that the first example is OK, and the last two have the problem.)? It isn't fixed for me. If you did, then it might be something local, although I can't really think what it could be. I have installed all dependencies including numpy from the anaconda distribution, and built from source trendvis and matplotlib, in a conda environment

**Comment by stefanv** [comment]
You're right!  I can reproduce the failures in those examples.

**Comment by jorgesca** [comment]
Thanks Stefan, I was going crazy thinking this could be a local installation issue. Unfortunately, even though I spent time trying to debug the issue (learning to set up conda envs, and using ipdb on the way), my knowledge of the inner workings of matplotlib (and even python) is too shallow

**Comment by efiring** [comment]
Apparently not current.  Closing.
