### ISSUE TITLE
pyplot fill_between warning since upgrade of numpy to 1.10.10

### ISSUE THREAD

**Issue by mhooreman** [matplotlib/matplotlib#5209]
Hello,

Since I've upgraded my python 3 environment, I get a warning, as demonstrated below:

    %matplotlib inline
    import matplotlib.pyplot as plt
    plt.fill_between([0, 1], [0, 1])

This gives the warning:

    /usr/local/lib/python3.4/dist-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
        if self._edgecolors == str('face')

The upgraded libraries are listed below, I'm pretty sure that this comes from the numpy upgrade

- Pillow: 2.9.0 -> 3.0.0
- XlsxWriter: 0.7.3 -> 0.7.5
- numpy: 1.9.3 -> 1.10.0
- path.py: 8.1.1 -> 8.1.2
- pexpect: 3.3 -> 4.0.1
- psutil: 3.2.1 -> 3.2.2
- requests: 2.7.0 -> 2.8.0

Best regards.

**Comment by jenshnielsen** [comment]
Which version of matplotlib? I think we have already fixed this on master and it will be in matplotlib 1.5.0 

At the moment you can ignore the warning. It will not actually break anything before Numpy actually makes the change.

**Comment by tlnagy** [comment]
I also ran into this problem with numpy v1.10.0 and matplotlib 1.4.3

**Comment by jenshnielsen** [comment]
Please test if this is still an issue with 1.5.0rc2 or master. I think we have already fixed this between 1.4.3 and the current master

**Comment by jenshnielsen** [comment]
Closing as this is fixed in master https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/collections.py#L624

**Comment by mhooreman** [comment]
Thanks a lot.

Do you have any idea of the release date of the 1.5.0?

Best regards.

**Comment by tacaswell** [comment]
"soon", I think we are down to documentation related issues.

https://github.com/matplotlib/matplotlib/milestones/next%20point%20release%20(1.5.0)

**Comment by pm0kjp** [comment]
I've upgraded to matplotlib 1.5.1, but still get the error when doing a scatterplot (regular plot is no problem...)  Any ideas?  Should I downgrade numpy?

**Comment by jenshnielsen** [comment]
@pm0kjp The original issue should be fixed but you are perhaps seeing something similar. Can you please provide a minimal example that demonstrates the issue that you are seeing. Also this is not an error with the latest release of numpy but a warning that something will change in the future thus there is no reason to downgrade numpy.

**Comment by fretchen** [comment]
I've upgraded to matplotlib 1.5.1, but still get the error when doing a fill_between.

**Comment by jenshnielsen** [comment]
@fretchen Do you mean warning rather than error? AFAIK no released version of numpy raises an error here but it does raise a warning.

Furthermore I cannot reproduce the warning in the original example at the top of this bug report. 
Can you please provide an example of what you are doing?

Original example:
```python
import matplotlib.pyplot as plt
plt.fill_between([0, 1], [0, 1])
plt.show()
```

Running this with Matplotlib 1.4.3 I see the warning:

```
/Users/jhn/Envs/mpl143/lib/python3.5/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):
```

But I don't see the warning with Matplotlib 1.5.1

**Comment by fretchen** [comment]
I am sorry. I forgot to restart the kernel after I installed the matplotlib. So consider my comment to be irrelevant.

**Comment by jenshnielsen** [comment]
@fretchen no problem

**Comment by xhain** [comment]
Have the same issue as OP, getting:

`.../anaconda3/lib/python3.5/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):`

**Comment by QuLogic** [comment]
You need to upgrade Matplotlib. There is no such line in the current release and even this issue was fixed in 1.5.0.
