### ISSUE TITLE
fig.suptitle() still scrambled with ax.title when using tight_layout()

### ISSUE THREAD

**Issue by michaelaye** [matplotlib/matplotlib#5355]
I don't know if the suptitle() is implemented via `OffsetBoxes`, but the `What's New` text mentioning this:

> When tight_layout() or Figure.tight_layout() or GridSpec.tight_layout() is called, OffsetBoxes that are     anchored outside the axes will not get chopped out. The OffsetBoxes will also not get overlapped by    other axes in case of multiple subplots.

made me hope that I could finally use fig.suptitle() with ax.title and fig.tight_layout() without manually adapting the margins. Alas, this still seems to be an issue:

![screenshot 2015-10-29 22 55 08](https://cloud.githubusercontent.com/assets/69774/10838765/9f933010-7e90-11e5-8bb8-f8161ab87840.png)

Version: '1.5.0rc3+207.g54ead93' on OSX, self compiled using `python setup.py install` with conda's Python 3.5

Code:

``` python
fig, ax = plt.subplots()
fig.suptitle('suptitle')
ax.plot(range(10))
ax.set_title('title')
fig.tight_layout()
```

**Comment by daeyun** [comment]
Any update on this?

**Comment by jklymak** [comment]
This doesn't work in tight_layout, but it does work in constrained_layout...  

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(constrained_layout=True)
fig.suptitle('suptitle')
ax.plot(range(10))
ax.set_title('title')
```

![suptitle](https://user-images.githubusercontent.com/1562854/48954431-5336bc00-eefe-11e8-8b70-fbc28f5d3e8a.png)

**Comment by jklymak** [comment]
My guess is that there is no good reason this could not be made to work in `tight_layout`, except tha `tight_layout` would need a good overhaul to include other artists not in the direct gridspec of the subplots.  #6914 was a partial solution to this, but what is really needed is for gridspecs to follow a proper nested hierarchy.  Given that `constrained_layout` works for all but the most complicated layouts, I'm not sure there is strong demand to do the extra work on `tight_layout` which is more modest in what it can accomplish.

**Comment by jklymak** [comment]
I'm going to close this as fixed in `constraind_layout` and I doubt anyone is going to fix in `tight_layout`.  But feel free to re-open if that's not the case....

**Comment by asteppke** [comment]
Unfortunately this is still not working in matplotlib 3.0.2 using `constrained_layout`. Under certain circumstances the layout still overlaps as shown in the following examples in the Jupyter notebook (with different backends):

```python
%matplotlib notebook 
import numpy as np
from matplotlib import pyplot as plt

# example with low height
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(6, 3), constrained_layout=True)
axes[0,0].plot([0,1,2], label='test')
axes[1,0].plot([0,1,2], label='test 2')
fig.suptitle('a longer title') 
```

This results in
![image](https://user-images.githubusercontent.com/5851636/54355839-6c54ab80-465a-11e9-8c29-ecc19e7cebf7.png)

But now increasing the plot height using the modified example
    
```python
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(6, 12), constrained_layout=True)
```

shows the following overlapping title:

![image](https://user-images.githubusercontent.com/5851636/54355911-9ad28680-465a-11e9-89b8-0c61cf9fc6d2.png)

Is there anything that can be done here to find out why this is not taking into account the larger plot dimensions?

**Comment by jklymak** [comment]
I can reproduce that. Basically the baseline of the subtitle *is* being aligned properly, but its overlapping the tick label and the descending "g" is going too deep.  I think its all fixable.  

However, I do have to make the figure quite large for this to happen.

**Comment by jklymak** [comment]
Can you open a new issue?  This is really a refinement of the old one...

**Comment by RylanSchaeffer** [comment]
what's the solution to this?

**Comment by jklymak** [comment]
suptitle is not compatible with `tight_layout`.  The solution is to use `constrained_layout` or place manually.

**Comment by timhoffm** [comment]
Can/should we warn if tight_layout is used with suptitle?
