### ISSUE TITLE
extra box on histogram plot with a single value

### ISSUE THREAD

**Issue by idavydov** [matplotlib/matplotlib#6959]
On a histogram with a single value repeated for 100 times I get an extra tiny box.
The code to reproduce the issue:
```python
from matplotlib import pylab as plt
plt.hist([33]*100)
plt.show()
```

Here you can see a black line next to 32.6.
![figure_1](https://cloud.githubusercontent.com/assets/671660/17805532/3ed8d7e0-6600-11e6-97ea-893a87e77ef6.png)

- Matplolib: 1.5.1-1ubuntu1 (from repository), Python 2.7.12, Ubuntu 16.04.1
- The same problem can be reproduced in python 3.5.2.

**Comment by LindyBalboa** [comment]
This one also appears to be fixed in the master branch. Python 3.5.2 on Ubuntu 16.04.

**Comment by WeatherGod** [comment]
"fixed"... probably hidden due to changes in style. I don't think the black
outlines happen in the default 2.0 styles?

**Comment by jenshnielsen** [comment]
@WeatherGod Yes I think you are right this is the black edge rendered incorrectly around the first bin. I think this is essentially a duplicate of 
#4212

**Comment by idavydov** [comment]
This bug is still present in the latest git version (2cdb5aab4f2a623185182f4e812e120c208bcedc).

It's only visible if default theme is used (probably related to outline shown/hidden):

```python
from matplotlib import pylab as plt
plt.style.use('classic')
plt.hist([33]*100)
plt.show()
```

![figure_1_bad2](https://cloud.githubusercontent.com/assets/671660/17813059/0f92c2be-662a-11e6-89bb-f3b2b5953907.png)

**Comment by jenshnielsen** [comment]
This was done as a fix for #408 In this case I think the cure is worse than the original problem so we should probably revert #408, I can't reproduce the issue in #408 anyway (perhaps it is specific to the OSX backend which is no more)

**Comment by LindyBalboa** [comment]
I got as far as looking at the rectangle patch properties. I guess there is no substitute for having history with a project! Nice one Jens.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/pull/6887

**Comment by jenshnielsen** [comment]
Closed by #6887
