### ISSUE TITLE
symlog + minor ticks = exception

### ISSUE THREAD

**Issue by LevN0** [matplotlib/matplotlib#6967]
Present in 1.5.1 and on 2.0.0b3, as well as master I think.

Enabling minor ticks via `minorticks_on` and having scale set to symlog raises an exception. In `minorticks_on`, the input passed to SymmetricalLogLocator is base and subs, but SymmetricalLogLocator is expecting transform and subs. Calling self._transform.base, when self._transform is a base (a float) causes exception,

> ...
>   File "C:\Python27_numpy\lib\site-packages\matplotlib\axis.py", line 900, in iter_ticks
>     minorLocs = self.minor.locator()
>   File "C:\Python27_numpy\lib\site-packages\matplotlib\ticker.py", line 1662, in **call**
>     return self.tick_values(vmin, vmax)
>   File "C:\Python27_numpy\lib\site-packages\matplotlib\ticker.py", line 1665, in tick_values
>     b = self._transform.base
> AttributeError: 'float' object has no attribute 'base'

Minimum code to reproduce,

```
import matplotlib.pyplot as plt

plt.plot([1,2,3,4])

ax = plt.gca()
ax.set_xscale('symlog')
ax.set_yscale('symlog')
ax.minorticks_on()

plt.show()
```

**Comment by tacaswell** [comment]
This went in via a6716df0eb65198b3ff0fbb6e49543ade5f5d985 from @Tillsten (but without a test).  I am not sure this has ever actually worked.

**Comment by pqrs6** [comment]
It seems like the issue has something to do with the way the `SymmetricalLogLocator` was implemented in the first place. The current implementation seems to explicitly exclude all ticks within the linear regime.

A custom solution described [http://stackoverflow.com/questions/20470892/how-to-place-minor-ticks-on-symlog-scale/20495928#20495928](here) seems to mostly solve the issue, which could be absorbed into the repository.

**Comment by tacaswell** [comment]
closed by #8367

**Comment by archman** [comment]
I've encountered this bug with 1.5.1 today, it's good to know the issue has been fixed in the newer release. While here is the trick to work around with version 1.5.1:
```python
from matplotlib.ticker import AutoMinorLocator
from matplotlib.ticker import NullLocator
# turn minor ticks on
self.axes.xaxis.set_minor_locator(AutoMinorLocator())
self.axes.yaxis.set_minor_locator(AutoMinorLocator())
# turn minor ticks off
self.axes.xaxis.set_minor_locator(NullLocator())
self.axes.yaxis.set_minor_locator(NullLocator())

**Comment by guido-granda** [comment]
Hi, 
I'm using matplotlib 3.3.4 and it looks like this usse is not fixed.
