### ISSUE TITLE
LaTeX wrong symbol displayed for sup- and subscript

### ISSUE THREAD

**Issue by mxmlnkn** [matplotlib/matplotlib#6976]
Platform:
- `uname -a` -> `Linux LenovoE330 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
- `dpkg -l '*matplotlib*'` -> `python-matplotlib        1.4.2-3.1   amd64`, `python-matplotlib-data   1.4.2-3.1`
  - `dpkg -l 'python'` -> `ii  python    2.7.11-2    amd64`
  - Everthing installed using `sudo apt-get install -t sid pyhton python-matplotlib`

This short example:

```
from matplotlib.pyplot import *
subplot( 111, title=r"$\mathcal{O}\left( N^3 \right)$" )
show()
```

renders to (cropped only title):

![n3-0](https://cloud.githubusercontent.com/assets/6842824/17966659/f1c226ce-6ac2-11e6-85b4-d29793984fe5.png)

But it should render to:

![n3fontfamily-0](https://cloud.githubusercontent.com/assets/6842824/17966672/ff334b3a-6ac2-11e6-9a16-87e71c070f01.png)

The latter was created by manually changing the example to:

```
from matplotlib.pyplot import *
matplotlib.rc('text', usetex=True)
subplot( 111, title=r"$\mathcal{O}\left( N^3 \right)$" )
show()
```

Therefore it seems that the problem is only with the internal mathtext rendering, not with LaTeX per se.
The problem also disappears when using `N^\mathregular{3}` and `\mathbb{3}`, but reappears when using `N^\mathit{3}` or `N^\mathrm{3}`.

See also https://stackoverflow.com/questions/14733605/python-matplotlib-label-title-wrong-character

**Comment by jenshnielsen** [comment]
I cannot reproduce the issue with either Matplotlib 1.4.3 or Matplotlib 1.5.2 

Im not sure if this is a bug fixed in 1.4.3 or something specific to your system or the Debian package.

**Comment by mxmlnkn** [comment]
I updated to matplotlib 1.5.2 and I can still reproduce the problem.
Also about you not being able to reproduce it:
I only have this problem on my notebook. On my PC it works fine. If I knew what I should compare between these two, I could do some tests. Maybe some font dependencies are not installed by default? On my PC I installed quite a bit more fonts because I had unicode problems.

**Comment by jenshnielsen** [comment]
It sounds like a font which has symbols interchanged or some such thing. Normally Matplotlib ships with it's own default font which is bitstream vera sans in 1.5/1.4 as far as I remember. The debian package probably changes this to a system font.

Can you try removing the matplotlib font cache. It should be stored in `matplotlib.get_cachedir()` and try again

**Comment by mxmlnkn** [comment]
After removing it the problem still persists. The output showed that the font-cache was indeed rebuilt:

    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
      warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

**Comment by jenshnielsen** [comment]
Interesting, does it happen if you explicitly select a different font as in your other example but without setting `use_tex` ?

**Comment by jenshnielsen** [comment]
In my question above I seemed to remember that you had something to set the font in your example. Did you modify it or am I just confused?

**Comment by mxmlnkn** [comment]
This

    from matplotlib.pyplot import *
    matplotlib.rc('font',**{'family':'sans-serif','sans-serif':['Helvetica']})
    #matplotlib.rc('text', usetex=True)
    subplot( 111, title=r"$\mathcal{O}\left( N^3 \right)$" )
    show()

does not work. But this:

    from matplotlib.pyplot import *
    print "old default mathrm-font =",matplotlib.rcParams['mathtext.rm']
    matplotlib.rcParams['mathtext.fontset'] = 'custom'
    matplotlib.rcParams['mathtext.rm'] = 'Bitstream Vera Sans'
    matplotlib.rcParams['mathtext.it'] = 'Bitstream Vera Sans:italic'
    matplotlib.rcParams['mathtext.bf'] = 'Bitstream Vera Sans:bold'
    subplot( 111, title=r"$\mathcal{O}\left( N^3 \right)$" )
    show()

works. 

![n3fontrmugly-0](https://cloud.githubusercontent.com/assets/6842824/17969481/864dc014-6ad2-11e6-82f3-ce5e29752616.png)

But the font now looks ugly and `\mathcal` does not seem to work anymore.
The output could hint to why `\mathcal` does not work:

    old default mathrm-font = serif
    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1288: UserWarning: findfont: Font family [u'cursive'] not found. Falling back to Bitstream Vera Sans
      (prop.get_family(), self.defaultFamily[fontext]))

Note: Before rebuilding the font cache the warnings were much more verbose:

    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1279: UserWarning: findfont: Font family ['cursive'] not found. Falling back to Bitstream Vera Sans
      (prop.get_family(), self.defaultFamily[fontext]))
    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1289: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=normal:variant=normal:weight=normal:stretch=normal:size=12.0. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
      UserWarning)
    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1279: UserWarning: findfont: Font family ['Bitstream Vera Sans'] not found. Falling back to Bitstream Vera Sans
      (prop.get_family(), self.defaultFamily[fontext]))
    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1289: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=italic:variant=normal:weight=normal:stretch=normal:size=12.0. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
      UserWarning)
    /usr/lib/python2.7/dist-packages/matplotlib/font_manager.py:1289: UserWarning: findfont: Could not match :family=Bitstream Vera Sans:style=normal:variant=normal:weight=bold:stretch=normal:size=12.0. Returning /usr/share/matplotlib/mpl-data/fonts/ttf/cmb10.ttf
      UserWarning)

**Comment by mxmlnkn** [comment]
Yes sorry, I did modify my first post, because I noticed that the useTex was the important bit. The changed font didn't seem to contribute to the fix. I'll refrain from editing, sry. In the above post I included the line to change the font like it was in the first post.

**Comment by jenshnielsen** [comment]
No problem, unfortunately I am running out of both time and good ideas at the moment. Will try to get back to this later

**Comment by mxmlnkn** [comment]
I tried an strace for .ttf fonts.
This is on the working system:

    open("/usr/share/fonts/truetype/ttf-bitstream-vera", O_RDONLY|O_CLOEXEC) = 4
    open("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", O_RDONLY) = 4
    open("/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf", O_RDONLY) = 7
    open("/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf", O_RDONLY) = 8
    open("/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf", O_RDONLY) = 9
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf", O_RDONLY) = 10
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf", O_RDONLY) = 11
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf", O_RDONLY) = 12

and this is on the non-working system:


    open("/usr/share/fonts/truetype/ttf-bitstream-vera", O_RDONLY|O_CLOEXEC) = 4
    open("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", O_RDONLY) = 4
    open("/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf", O_RDONLY) = 7
    open("/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf", O_RDONLY) = 8
    open("/usr/share/fonts/truetype/ttf-bitstream-vera/Vera.ttf", O_RDONLY) = 9
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf", O_RDONLY) = 10
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf", O_RDONLY) = 11
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf", O_RDONLY) = 12
    open("/usr/share/matplotlib/mpl-data/fonts/ttf/cmex10.ttf", O_RDONLY) = 13

The only difference is `cmex10.ttf` which is additionally queried for in the non-working/omega-version.

**Comment by jenshnielsen** [comment]
Are the two machines running the same Debian version? I am just thinking if it could be possible that the font file is buggy on one of the machines?

**Comment by mxmlnkn** [comment]
And while the bitstream and dejavu fonts have the same md5sum the md5sums for the `mpl-data` fonts do differ for some reason. On both systems the exact same package should be installed:


    md5sum "/usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf" \
           "/usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf" \
           "/usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf"  \
           "/usr/share/matplotlib/mpl-data/fonts/ttf/cmex10.ttf"

non-working:

    d44df18d5f10d2d31f12705d418f3ab9  /usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf
    3d424c159d373a07f41b91443cd75d3a  /usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf
    74e007d22b2294d5eba8f2593875eff3  /usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf
    f1566d907653315b9cc640be07f2748b  /usr/share/matplotlib/mpl-data/fonts/ttf/cmex10.ttf

working:

    567750b4181f771246a94ba6942ea5fb  /usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf
    f9eece337f6fbef33126ed2ccdfa13dd  /usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf
    9b4726982be9203f0115dce99194d05b  /usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf
    c89254bbab0ffa4f3b5dcc2b0e49af3f  /usr/share/matplotlib/mpl-data/fonts/ttf/cmex10.ttf

@jenshnielsen Both systems should run the same version (Debian sid), but I install updates rather individually like I need them, so it could be that they differ in many packages.

**Comment by jenshnielsen** [comment]
and the fonts in `/usr/share/matplotlib/mpl-data/fonts` are all coming from the same version of the  matplotlib debian package? that is strange

**Comment by mxmlnkn** [comment]
I found out, that the paths to the fonts were symbolic links, so I thought that maybe md5sum calculated the checksum of the symbolic links itself instead of following them:

    md5sum                                                             \
    $(readlink -f /usr/share/matplotlib/mpl-data/fonts/ttf/cmsy10.ttf) \
    $(readlink -f /usr/share/matplotlib/mpl-data/fonts/ttf/cmmi10.ttf) \
    $(readlink -f /usr/share/matplotlib/mpl-data/fonts/ttf/cmr10.ttf ) \ 
    $(readlink -f /usr/share/matplotlib/mpl-data/fonts/ttf/cmex10.ttf)

working system:

    567750b4181f771246a94ba6942ea5fb  /usr/share/fonts/truetype/lyx/cmsy10.ttf
    f9eece337f6fbef33126ed2ccdfa13dd  /usr/share/fonts/truetype/lyx/cmmi10.ttf
    9b4726982be9203f0115dce99194d05b  /usr/share/fonts/truetype/lyx/cmr10.ttf
    md5sum: ' ': No such file or directory
    -bash: /usr/share/fonts/truetype/lyx/cmex10.ttf: Permission denied

Non-working:

    d44df18d5f10d2d31f12705d418f3ab9  /usr/share/fonts/truetype/lyx/cmsy10.ttf
    3d424c159d373a07f41b91443cd75d3a  /usr/share/fonts/truetype/lyx/cmmi10.ttf
    74e007d22b2294d5eba8f2593875eff3  /usr/share/fonts/truetype/lyx/cmr10.ttf

But that was not the case. But using `dpkg -S` on the followed paths of the symlinks, show that the fonts don't come from `python-matplotlib-data`, but from `fonty-lyx!

    dpkg -S /usr/share/fonts/truetype/lyx/cmex10.ttf
        fonts-lyx: /usr/share/fonts/truetype/lyx/cmex10.ttf
        
Simple file size and other information:

    'ls' -l \
    /usr/share/fonts/truetype/lyx/cmsy10.ttf \
    /usr/share/fonts/truetype/lyx/cmmi10.ttf \
    /usr/share/fonts/truetype/lyx/cmr10.ttf  \
    /usr/share/fonts/truetype/lyx/cmex10.ttf
    
non working:

    -rw-r--r-- 1 root root 20688 Jul  2 10:08 /usr/share/fonts/truetype/lyx/cmex10.ttf
    -rw-r--r-- 1 root root 32036 Jul  2 10:08 /usr/share/fonts/truetype/lyx/cmmi10.ttf
    -rw-r--r-- 1 root root 26188 Jul  2 10:08 /usr/share/fonts/truetype/lyx/cmr10.ttf
    -rw-r--r-- 1 root root 28476 Jul  2 10:08 /usr/share/fonts/truetype/lyx/cmsy10.ttf

Working:

    -rw-r--r-- 1 root root 21092 Sep 17  2015 /usr/share/fonts/truetype/lyx/cmex10.ttf
    -rw-r--r-- 1 root root 32556 Sep 17  2015 /usr/share/fonts/truetype/lyx/cmmi10.ttf
    -rw-r--r-- 1 root root 26348 Sep 17  2015 /usr/share/fonts/truetype/lyx/cmr10.ttf
    -rw-r--r-- 1 root root 29392 Sep 17  2015 /usr/share/fonts/truetype/lyx/cmsy10.ttf

Try for `fonts-lynx` version:

    dpkg -l 'fonts-lyx'
    
working:

    ii  fonts-lyx 2.1.4-2 all TrueType versions of some TeX fonts used by LyX

non-working

    ii  fonts-lyx 2.2.0-2 all TrueType versions of some TeX fonts used by LyX

Try downgrading on non-working system.

    sudo apt-get install fonts-lyx=2.1.4-2
        E: Version '2.1.4-2' for 'fonts-lyx' was not found
    scp working:/var/cache/apt/archives/fonts-lyx_2.1.4-2_all.deb .
    sudo dpkg -i fonts-lyx_2.1.4-2_all.deb
    python texmatplotlibbug.py
        ERROR GONE
    sudo apt-get install -t sid fonts-lyx
    python texmatplotlibbug.py
        ERROR BACK!

apt-cache show python-matplotlib-data

    Package: python-matplotlib-data
    Source: matplotlib
    Version: 1.5.2~rc2-1
    Installed-Size: 5695
    Maintainer: Sandro Tosi <morph@debian.org>
    Architecture: all
    Depends: fonts-lyx, ttf-bitstream-vera
    Description-en: Python based plotting system (data package)
     Matplotlib is a pure Python plotting library designed to bring
     publication quality plotting to Python with a syntax familiar to
     Matlab users. All of the plotting commands in the pylab interface can
     be accessed either via a functional interface familiar to Matlab
     users or an object oriented interface familiar to Python users.
     .
     This package contains architecture independent data for python-matplotlib.
    Description-md5: a392280ebaa89b347e0cd9caaa019b0c
    Homepage: http://matplotlib.org/
    Tag: role::app-data
    Section: python
    Priority: optional
    Filename: pool/main/m/matplotlib/python-matplotlib-data_1.5.2~rc2-1_all.deb
    Size: 2900928
    MD5sum: eefb8d062ae562cccca3b1b63a009fa3
    SHA1: cad1662b4b02e4f73fb9c2230de316f7f9503730
    SHA256: e92d727d4ad220405b5ea2e98d6ad34ee31dd674669a189ea7b72538b2eb87af

 => fonts-lyx is set as a dependency, but no exact version is specified, resulting in the bug.

The stackoverflow question was posed 3 years ago, so I don't think this problem is specific to fonts-lyx 2.1.4 vs. 2.2.0, instead it seems to me that every version change in fonts-lys will most likely result in this bug.

**Comment by tacaswell** [comment]
attn @sandrotosi any idea what is going on with debian + fonts?  Where is the right place to report this to debian as an issue?

@mxmlnkn Thanks for your work tracking this down!

**Comment by tacaswell** [comment]
Likely related:

https://github.com/matplotlib/matplotlib/issues/6617

https://github.com/matplotlib/matplotlib/issues/6665

**Comment by jniediek** [comment]
I can reproduce problem and solution.

**Configuration with broken TeX rendering**
Debian testing/unstable
`python-matplot = 1.5.2~rc2`
`fonts-lyx = 2.2.0-ii`

**My work-around (thanks to the posts in this thread)**
`wget http://archive.ubuntu.com/ubuntu/pool/universe/l/lyx/fonts-lyx_2.1.4-2_all.deb`
`dpkg -i fonts-lyx_2.1.4-2_all.deb`

After this, TeX rendering works again.

**Comment by sandrotosi** [comment]
this is a bug in the fonts-lyx package (i think), and so i just reported it to them: http://bugs.debian.org/836329

**Comment by mhvk** [comment]
I had the same problem -- thanks very much for the solution posted here!

Note that the LyX maintainers suggest there is a problem with matplotlib as well:

> 2) The font replacement algorithm used by matplotlib has a bug. It seems it uses some kind of symbol font which causes the omega instead of the superscript 3. This symbol does not come from the additionally queried cmex10.ttf font, I believe this font is tested because cmr10.ttf did not work, but is then discarded as well.

**Comment by tacaswell** [comment]
@mhvk where does that pull quote come from?  Direct discussion can make these sorts of issues go away quickly.

**Comment by mhvk** [comment]
@tacaswell - sorry, it was exactly my intent to ensure people knew what others had said elsewhere but I should have been explicit: that the quote was from the debian bug report that @sandrotosi filed, which was linked in his comment above mine: see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836329#12

**Comment by sandrotosi** [comment]
lemme ask on that bug do come and discuss that matter here, to close the gap

**Comment by Kohlrabi** [comment]
I found that using
`matplotlib.rcParams['mathtext.fontset'] = 'stix'`
or adding
`mathtext.fontset : stix`
to the matplotlibrc solved the issue for me as well, without the "ugly" LaTeX rendering of labels, even with fonts-lyx 2.2.0-2 installed.

**Comment by raphaelm** [comment]
I can confirm @kohlrabi's woraround do work.

**Comment by jkseppan** [comment]
attn @sandrotosi 

I'm not sure that this is really a bug in the other package, it's just that it's meant for use by LyX and modifies the original bakoma fonts to suit LyX better. I think the Debian packaging of matplotlib shouldn't depend on the LyX-modified version of these fonts but bundle the bakoma versions as included in the matplotlib git repository. I have version 2.1.2-2 on my test system, and the `ReadmeBaKoMa4LyX.txt` file includes the following text:

>       The fonts included in this package are taken from
> 
>       http://www.ctan.org/tex-archive/fonts/cm/ps-type1/bakoma/ttf/
> 
>       and have been modified for use with LyX. 
>       The most recent versions of the original fonts are available 
>       with the complete BaKoMa TeX distribution at
> 
>       http://www.ctan.org/tex-archive/systems/win32/bakoma/
> 
>       The author of these fonts, Basil K. Malyshev, has kindly
>       granted permission to use and modify these fonts.
>      
>       The changes made are simple remappings of glyphs. These mappings
>       are:
> 
>       cmsy10.ttf   char 8728 mapped to char 183 (\leq)
>       cmsy10.ttf   char  196 mapped to char 127 (\spadesuit)
>       msbm10.ttf   char 8728 mapped to char 183 (\nleqq)
>       msbm10.ttf   char  196 mapped to char 127 (\backepsilon)
>       cmmi10.ttf   char 8728 mapped to char 183 (\kapp)
>       msam10.ttf   char  196 mapped to char 127 (\circleddash)
>       msam10.ttf   char 8728 mapped to char 183 (\uparrows)

I assume the newer version has further remappings that cause matplotlib's assumptions about bakoma character encoding to fail.

**Comment by sandrotosi** [comment]
oh nice catch @jkseppan - i'll revert the package to use the fonts included with mpl tarball

FTR, this is was we were doing:

```
        # link to fonts in ttf-lyx
        for font in cmex10.ttf cmmi10.ttf cmr10.ttf cmsy10.ttf ; \
        do \
            ln -sf /usr/share/fonts/truetype/lyx/$$font $(CURDIR)/debian/$(pdata)/usr/share/matplotlib/mpl-data/fonts/ttf/$$font; \
        done
```

**Comment by jonassmedegaard** [comment]
The web page http://www.ctan.org/tex-archive/systems/win32/bakoma/ referenced in file ReadmeBaKoMa4LyX.txt describes the fonts as Shareware.  At other places - e.g. http://www.math.utah.edu/~beebe/fonts/bakoma.html - the BaKoMa fonts are described as "free" but only for non-commercial use.

@jkseppan I recommend to add a file in same folder as the BaKoMa fonts where you clarify its license - including quoting verbatim the licensing terms as they were given to you from Basil - directly or possibly via redistribution, but not hearsay.

If project A receives the fonts and a license for using them, but then redistributes the fonts _without the license, then project B is not licensed to use the fonts!

Debian now have a problem that it cannot "re-add" a license that got lost in transit (from LyX to matplotlib) - and matplotlib project might have the same problem.

**Comment by anntzer** [comment]
If I understand correctly this has been fixed by Debian.  Feel free to reopen if not.
