### ISSUE TITLE
Weird stroke join with patheffects

### ISSUE THREAD

**Issue by dopplershift** [matplotlib/matplotlib#7822]
So I used the following code to draw some outlined text at large size with matplotlib 2.0.0rc2 (on macOS 10.12.2) using the Agg backend, installed from conda-forge on Python 3.5.2:

```python
from datetime import datetime

from matplotlib import patheffects
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(6, 2), dpi=300)
ax = fig.add_axes([0.03, 0.03, 0.95, 0.95])
timestamp = datetime(1999, 5, 4, 0)
text = ax.text(0.99, 0.6, timestamp.strftime('%d %B %Y %H%MZ'),
               horizontalalignment='right', transform=ax.transAxes,
               color='white', fontsize=36, weight='bold')
text.set_path_effects([patheffects.Stroke(linewidth=6, foreground='black'),
                       patheffects.Normal()])
plt.savefig('test-stroke.png')
```

This gives:

![image](https://cloud.githubusercontent.com/assets/221526/21947239/777293ba-d9a1-11e6-9a68-9d086fdb33a0.png)

Notice the missing wedge of outline at the bottom of the 9's.

**Comment by tacaswell** [comment]
I could have sworn we fixed this....Maybe it is just on master?

**Comment by dopplershift** [comment]
I can run on master...

**Comment by dopplershift** [comment]
Still seeing it on my build of master--you may want to verify for yourself.

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/issues/7064

**Comment by dopplershift** [comment]
So setting the capstyle to "rounded" is a work-around, but it seems like there's a real bug here. I don't buy the idea that it's because the strokes come in at different angles--otherwise most of the letter should show a problem somewhere.

Or if it is expected, should be set the default capstyle to rounded?

**Comment by QuLogic** [comment]
This is a dupe of #7227.
