### ISSUE TITLE
Rectangle patch not transformed correctly in polar plot

### ISSUE THREAD

**Issue by alexvorndran** [matplotlib/matplotlib#8521]
**Bug summary**
I added some rectangular patches to a polar plot and found that they are not transformed correctly if those patches are the only objects plotted. However, if there is any plot like a polar bar plot on the same figure, all patches on this and following figures are displayed correctly. As you can see in the code below, this behaviour can be observed even if the "other" plot is removed immediately.

Please note that this will only work on a "fresh" IPython/python console where no bar/scatter/... plot has been done on a polar axis, as all subsequent attempts will produce the correct result.

**Code for reproduction**

Putting ```plt.show()``` at the very end of the script instead of where it is in the snippet does not lead to the error described above.

```python
# -*- coding: utf-8 -*-
import math

import matplotlib.pyplot as plt
from matplotlib import patches


def polarbug(bar_hack=False):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='polar')

    # add quadrant as example
    ax.add_patch(
        patches.Rectangle(
            (0, 1), width=math.pi*0.5, height=0.5
        )
    )

    if bar_hack:
        ax.bar(0, 1).remove()

    ax.set_rmax(2)
    plt.show()


if __name__ == '__main__':
    polarbug()
    polarbug(bar_hack=True)
    polarbug()
```

**Actual outcome**
With (left) and without (right) ```ax.set_rmax(2)```:
Figure 1
![polarbug-1](https://cloud.githubusercontent.com/assets/8378614/25256823/02c6c2b8-2634-11e7-857c-5fb8151dd45a.png) ![polarbug-1-w](https://cloud.githubusercontent.com/assets/8378614/25256855/36584034-2634-11e7-9e1b-62bfa445ed80.png)

Figure 2
![polarbug-2](https://cloud.githubusercontent.com/assets/8378614/25256829/0c944400-2634-11e7-925c-4e2f5115f979.png) ![polarbug-2-w](https://cloud.githubusercontent.com/assets/8378614/25256857/3c38c870-2634-11e7-91fa-bcdffe9e2a89.png)

Figure 3
![polarbug-3](https://cloud.githubusercontent.com/assets/8378614/25256830/0d0894ea-2634-11e7-8e48-e890d53ed68e.png) ![polarbug-3-w](https://cloud.githubusercontent.com/assets/8378614/25256863/4462507a-2634-11e7-95bd-4e1325a419af.png)

**Expected outcome**
All three figures should look the same.

**Matplotlib version**

  * Operating System: Windows 10 Pro x64
  * Matplotlib Version: 2.0.0 (conda 4.3.16)
  * Python Version: 2.7.13 64bit
  * Other Libraries: math or numpy (for pi only)

**Comment by phobson** [comment]
Thanks for the detailed report. I can confirm this.

**Comment by Tuan333** [comment]
Hi, I recently grew to be interested in internals of `matplotlib`, and was hoping to make some contributions. 

I noticed that when the `_AxesBase.bar()` function is called (especially the part just before it adds the `BarContainer`), the  *static* variable `Path._unit_rectangle._interpolation_steps` is set to 100 (which explains why the third graph looks like the second graph). Is there a particular reason why this static variable is not set in the function `_AxesBase.add_patch()`? 

I added `p.get_path()._interpolation_steps = 100` to line 1863 in `_base.py` to fix this problem. If you think it's a viable solution, I'll make a PR. Output from the above script with this should result to @alexvorndran 's expected result (three identical graphs looking like this 2nd and 3rd graphs).

**Comment by phobson** [comment]
@Tuan333 thanks for looking into the issue. I encourage to make that PR so that the people who are knowledgeable enough to know if that's a good solution can easily review your work.

**Comment by dstansby** [comment]
Fixed by #8539

**Comment by dopplershift** [comment]
Re-opening since the merge of #8539 has been reverted for the 2.1 series.

**Comment by mattpang** [comment]
I didn't know if I should submit a new issue, since the OP still shows this effect. I have another example pasted that I was testing which repeats the same issue, but clunkier. 

```
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Wedge
from matplotlib.collections import PatchCollection

if False:
    plt.figure()
    fig, ax = plt.subplots(figsize=[6,6], subplot_kw={'projection': 'polar'})
    ax.bar(x=np.deg2rad(12), height = 1.1, width=4.1, bottom=0.4)
    ax.scatter(np.deg2rad([12,3,45]),[4,5,3])
    plt.show()

if True:
    plt.figure()
    fig, ax = plt.subplots(figsize=[6,6], subplot_kw={'projection': 'polar'})
    ax.scatter(np.deg2rad([12,3,45]),[4,5,3])
    p = Rectangle((np.deg2rad(12), 5), np.deg2rad(94), 1.1, color='blue')
    ax.add_patch(p)
    plt.show()
```

**Comment by RaverJay** [comment]
Just ran into this bug, still exists today with mpl v3.7.2

**Comment by akrherz** [comment]
reproduced this issue now with v3.8.2, thankfully the `bar_hack` workaround it.

**Comment by akrherz** [comment]
Still reproduces on 3.10.1

**Comment by rcomer** [comment]
See #9261 for why the previous fix was reverted at #9265.
